import { useTranslation } from 'react-i18next';
import i18n from '../i18n/configuracao';

const normalizarMojibake = (texto: string): string => {
  if (!texto) return texto;

  let atual = texto;
  for (let tentativa = 0; tentativa < 3; tentativa += 1) {
    if (!/[\u00C3\u00C2\u00E2\u00EF]/.test(atual)) break;
    try {
      const decodificado = decodeURIComponent(escape(atual));
      if (decodificado === atual) break;
      atual = decodificado;
    } catch {
      break;
    }
  }

  return atual;
};

const fallbackPorIdioma: Record<string, Record<string, string>> = {
  'pt-BR': {
    'comum.email': 'Email',
    'comum.senha': 'Senha',
    'comum.entrar': 'Entrar',
    'comum.sair': 'Sair',
    'menu.painelUsuario': 'Painel do Usuário',
    'comum.erro': 'Erro',
    'comum.sucesso': 'Sucesso',
    'comum.carregando': 'Carregando',
    'comum.acoes.selecionar': 'Selecionar',
    'comum.acoes.visualizar': 'Visualizar',
    'comum.acoes.editar': 'Editar',
    'comum.acoes.cancelar': 'Cancelar',
    'comum.acoes.salvar': 'Salvar',
    'comum.acoes.confirmar': 'Confirmar',
    'comum.acoes.remover': 'Remover',
    'dashboard.titulo': 'Dashboard',
    'dashboard.bem-vindo': 'Bem-vindo ao Core!',
    'dashboard.saudacao-usuario': 'Olá, {{nome}}! Você está logado como {{perfil}}.',
    'dashboard.informacoes': 'Informações do Usuário',
    'dashboard.modulos': 'Módulos Ativos',
    'dashboard.nenhum-modulo': 'Nenhum',
    'dashboard.proximos-passos': 'Próximos passos: Implementar módulo financeiro',
    'dashboard.globalTitle': 'Visão Geral Financeira',
    'dashboard.globalDescription': 'Acompanhe os principais indicadores financeiros, movimentações recentes, desempenho anual e o balanço consolidado de contas e cartões.',
    'dashboard.resumoFinanceiro': 'Resumo Financeiro',
    'dashboard.graficoAreaSubarea': 'Gráfico por Área e Subárea',
    'dashboard.graficoAreaSubareaDescricao': 'Ganhos e gastos consolidados por área e subárea no período filtrado.',
    'dashboard.graficoAreaSubareaCentro': 'Total Filtrado',
    'dashboard.graficoAnual': 'Gráfico Anual',
    'dashboard.ultimasTransacoes': 'Últimas Transações',
    'dashboard.balancoGeral': 'Balanço Geral',
    'dashboard.saldoAtualConta': 'Saldo Atual da Conta',
    'dashboard.saldoDisponivelCartao': 'Saldo Disponível do Cartão',
    'dashboard.widget': 'Widget',
    'dashboard.reordenarHint': 'Arraste os widgets ou use as setas para reorganizar a dashboard.',
    'dashboard.widgetGraficoInfo': 'Os valores acompanham o idioma selecionado e refletem o filtro aplicado.',
    'dashboard.cards.receitas': 'Receitas',
    'dashboard.cards.despesas': 'Despesas',
    'dashboard.cards.reembolsos': 'Reembolsos',
    'dashboard.cards.estornos': 'Estornos',
    'dashboard.cards.saldo': 'Saldo',
    'dashboard.widgets.resumo': 'Resumo Financeiro',
    'dashboard.widgets.graficoAreaSubarea': 'Gráfico por Área e Subárea',
    'dashboard.widgets.graficoAnual': 'Gráfico Anual',
    'dashboard.widgets.ultimasTransacoes': 'Últimas Transações',
    'dashboard.widgets.balancoGeral': 'Balanço Geral',
    'dashboard.colunas.id': 'ID',
    'dashboard.colunas.tipo': 'Tipo',
    'dashboard.colunas.valor': 'Valor',
    'dashboard.colunas.descricao': 'Descrição',
    'dashboard.colunas.dataEfetivacao': 'Data',
    'dashboard.colunas.tipoPagamento': 'Pagamento / Recebimento',
    'dashboard.colunas.contaBancaria': 'Conta Bancária',
    'dashboard.colunas.cartao': 'Cartão',
    'dashboard.colunas.areaSubarea': 'Área / Subárea',
    'dashboard.tipos.despesa': 'Despesa',
    'dashboard.tipos.receita': 'Receita',
    'dashboard.tipos.reembolso': 'Reembolso',
    'dashboard.tipos.estorno': 'Estorno',
    'dashboard.tiposBalanco.conta': 'Conta Bancária',
    'dashboard.tiposBalanco.cartao': 'Cartão',
    'dashboard.pagamento.PIX': 'PIX',
    'dashboard.pagamento.TRANSFERENCIA': 'Transferência',
    'dashboard.pagamento.CARTAO_CREDITO': 'Cartão de Crédito',
    'dashboard.pagamento.BOLETO': 'Boleto',
    'dashboard.pagamento.DINHEIRO': 'Dinheiro',
    'dashboard.contas.BANCO_XP': 'Banco XP',
    'dashboard.contas.BANCO_DIGITAL': 'Banco Digital',
    'dashboard.contas.ITAU': 'Itaú',
    'dashboard.contas.NUBANK': 'Nubank',
    'dashboard.contas.INTER': 'Inter',
    'dashboard.descricoes.ALMOCO_CLIENTE': 'Almoço com cliente',
    'dashboard.descricoes.VENDA_SERVICO': 'Venda de serviço',
    'dashboard.descricoes.REEMBOLSO_VIAGEM': 'Reembolso de viagem',
    'dashboard.descricoes.ESTORNO_COBRANCA': 'Estorno de cobrança',
    'dashboard.descricoes.ASSINATURA': 'Assinatura mensal',
    'dashboard.descricoes.SUPERMERCADO': 'Compra de supermercado',
    'dashboard.descricoes.COMBUSTIVEL': 'Abastecimento',
    'dashboard.descricoes.RECEBIMENTO': 'Recebimento recorrente',
    'dashboard.areas.OPERACOES': 'Operações',
    'dashboard.areas.COMERCIAL': 'Comercial',
    'dashboard.areas.PESSOAL': 'Pessoal',
    'dashboard.areas.LAZER': 'Lazer',
    'dashboard.areas.TECNOLOGIA': 'Tecnologia',
    'dashboard.areas.FINANCEIRO': 'Financeiro',
    'dashboard.areas.LOGISTICA': 'Logística',
    'dashboard.areas.JURIDICO': 'Jurídico',
    'dashboard.areas.ADMINISTRATIVO': 'Administrativo',
    'dashboard.areas.ATENDIMENTO': 'Atendimento',
    'dashboard.subareas.SUPRIMENTOS': 'Suprimentos',
    'dashboard.subareas.TRANSPORTE': 'Transporte',
    'dashboard.subareas.MANUTENCAO': 'Manutenção',
    'dashboard.subareas.VENDAS': 'Vendas',
    'dashboard.subareas.MARKETING': 'Marketing',
    'dashboard.subareas.EVENTOS': 'Eventos',
    'dashboard.subareas.SALARIOS': 'Salários',
    'dashboard.subareas.BENEFICIOS': 'Benefícios',
    'dashboard.subareas.TREINAMENTO': 'Treinamento',
    'dashboard.subareas.VIAGENS': 'Viagens',
    'dashboard.subareas.CINEMA': 'Cinema',
    'dashboard.subareas.RESTAURANTES': 'Restaurantes',
    'dashboard.subareas.SOFTWARE': 'Software',
    'dashboard.subareas.INFRAESTRUTURA': 'Infraestrutura',
    'dashboard.subareas.LICENCAS': 'Licenças',
    'dashboard.subareas.IMPOSTOS': 'Impostos',
    'dashboard.subareas.TARIFAS': 'Tarifas',
    'dashboard.subareas.INVESTIMENTOS': 'Investimentos',
    'dashboard.subareas.ARMAZENAGEM': 'Armazenagem',
    'dashboard.subareas.FRETES': 'Fretes',
    'dashboard.subareas.DISTRIBUICAO': 'Distribuição',
    'dashboard.subareas.CONTRATOS': 'Contratos',
    'dashboard.subareas.CONSULTORIA': 'Consultoria',
    'dashboard.subareas.PROCESSOS': 'Processos',
    'dashboard.subareas.FACILITIES': 'Facilities',
    'dashboard.subareas.VIAGENS_CORPORATIVAS': 'Viagens Corporativas',
    'dashboard.subareas.PATRIMONIO': 'Patrimônio',
    'dashboard.subareas.SUPORTE': 'Suporte',
    'dashboard.subareas.POS_VENDA': 'Pós-venda',
    'dashboard.subareas.OUVIDORIA': 'Ouvidoria',
    'financeiro.despesas': 'Despesas',
    'financeiro.receitas': 'Receitas',
    'financeiro.reembolsos': 'Reembolsos',
    'amigos.titulo': 'Amigos',
    'admin.titulo': 'Administração',
    'documentacao.titulo': 'Documentação - {{módulo}}',
    'documentacao.acao': 'Documentação',
    'documentacao.descricaoPadrao': 'Esta tela reúne os conteúdos publicados para o módulo {{módulo}}. As informações são mantidas pela administração.',
    'documentacao.vazio': 'Nenhuma documentação publicada para este módulo.',
    'documentacao.atualizadoEm': 'Atualizado em',
    'documentacao.modulos.dashboard': 'Dashboard',
    'documentacao.modulos.financeiro': 'Financeiro',
    'documentacao.modulos.amigos': 'Amigos',
    'documentacao.modulos.admin': 'Administração',
    'comum.login.esqueciSenha': 'Esqueci minha senha',
    'comum.login.esqueciSenhaSucesso': 'Se o email estiver cadastrado, as instrucoes de recuperacao serao enviadas.',
    'comum.login.credenciaisTeste': 'Use admin@core.com / 123456 para testar',
    'comum.login.tentativasRestantes': 'Tentativas restantes: {{tentativas}}',
    'comum.login.erros.camposObrigatorios': 'Email e Senha são obrigatórios',
    'comum.login.erros.emailInvalido': 'Informe um email valido',
    'comum.login.erros.emailObrigatorioRecuperacao': 'Informe o email para recuperar a senha',
    'comum.login.erros.credenciaisInvalidas': 'Credenciais invalidas. Tentativas restantes: {{tentativas}}',
    'comum.login.erros.bloqueadoTentativas': 'Login bloqueado apos 5 tentativas invalidas.',
    'primeiroAcesso.titulo': 'Crie sua senha de acesso',
    'primeiroAcesso.descricao': 'No primeiro login, e obrigatório definir uma nova senha.',
    'primeiroAcesso.campos.novaSenha': 'Nova senha *',
    'primeiroAcesso.campos.confirmarSenha': 'Confirmar nova senha *',
    'primeiroAcesso.botaoConfirmar': 'Confirmar senha',
    'primeiroAcesso.sucesso.senhaCriada': 'Senha criada com sucesso.',
    'primeiroAcesso.erros.camposObrigatorios': 'Preencha os dois campos de senha.',
    'primeiroAcesso.erros.senhaMinima': 'A senha deve ter no minimo 10 caracteres.',
    'primeiroAcesso.erros.confirmacaoDiferente': 'A confirmacao da senha esta diferente.',
    'primeiroAcesso.erros.falhaCriarSenha': 'Não foi possível criar a senha.',
    'usuarioPainel.titulo': 'Painel do Usuário',
    'usuarioPainel.informacoes': 'Informações do Usuário',
    'usuarioPainel.nome': 'Nome',
    'usuarioPainel.email': 'E-mail',
    'usuarioPainel.perfil': 'Perfil de Acesso',
    'usuarioPainel.alterarSenha': 'Alterar Senha',
    'usuarioPainel.campos.senhaAtual': 'Senha Atual *',
    'usuarioPainel.campos.novaSenha': 'Nova Senha *',
    'usuarioPainel.campos.confirmarSenha': 'Confirmar Nova Senha *',
    'usuarioPainel.botaoSalvar': 'Salvar Nova Senha',
    'usuarioPainel.sucesso.senhaAlterada': 'Senha alterada com sucesso.',
    'usuarioPainel.erros.camposObrigatorios': 'Preencha todos os campos de senha.',
    'usuarioPainel.erros.senhaMinima': 'A nova senha deve ter no minimo 10 caracteres.',
    'usuarioPainel.erros.confirmacaoDiferente': 'A confirmacao da senha esta diferente.',
    'usuarioPainel.erros.falhaAlterarSenha': 'Não foi possível alterar a senha.',
    'admin.documentacao.gerenciar': 'Gerenciar Documentações',
    'admin.documentacao.novo': 'Nova Documentação',
    'admin.documentacao.editar': 'Editar Documentação',
    'admin.documentacao.modulo': 'Módulo',
    'admin.documentacao.titulo': 'Título',
    'admin.documentacao.resumo': 'Resumo',
    'admin.documentacao.conteudo': 'Conteúdo',
    'admin.documentacao.placeholderTitulo': 'Digite o título da documentação',
    'admin.documentacao.placeholderResumo': 'Descreva rapidamente o objetivo deste conteúdo',
    'admin.documentacao.placeholderConteudo': 'Explique funcionalidades, regras e fluxos do módulo',
    'admin.documentacao.salvoSucesso': 'Documentação salva com sucesso.',
    'admin.documentacao.publicadoSucesso': 'Documentação publicada com sucesso.',
    'admin.documentacao.deletadoSucesso': 'Documentação removida com sucesso.',
    'admin.documentacao.confirmarDelete': 'Deseja remover esta documentação?',
    'admin.documentacao.erros.camposObrigatorios': 'Título, resumo e conteúdo são obrigatórios.',
    'financeiro.cartao.acoes.extrato': 'Extrato',
    'financeiro.cartao.extratoTitulo': 'Extrato de Gastos',
    'financeiro.cartao.extratoVazio': 'Nenhum gasto encontrado para o mês selecionado.',
    'financeiro.cartao.totalExtrato': 'Total do Extrato',
    'financeiro.cartao.titulo': 'Cartoes',
    'financeiro.cartao.novo': 'Novo Cartão',
    'financeiro.cartao.vazio': 'Nenhum cartão encontrado.',
    'financeiro.cartao.campos.descricao': 'Descrição *',
    'financeiro.cartao.campos.bandeira': 'Bandeira *',
    'financeiro.cartao.campos.tipo': 'Tipo *',
    'financeiro.cartao.campos.limite': 'Limite *',
    'financeiro.cartao.campos.saldoDisponivel': 'Saldo Disponível *',
    'financeiro.cartao.campos.diaVencimento': 'Dia de Vencimento *',
    'financeiro.cartao.campos.dataVencimentoCartao': 'Data de Vencimento do Cartão *',
    'financeiro.cartao.campos.status': 'Status',
    'financeiro.cartao.placeholders.descricao': 'Digite a descrição do cartão',
    'financeiro.cartao.placeholders.valor': '0,00',
    'financeiro.cartao.placeholders.data': 'DD/MM/AAAA',
    'financeiro.cartao.tipos.credito': 'Crédito',
    'financeiro.cartao.tipos.debito': 'Débito',
    'financeiro.cartao.status.ativo': 'ATIVO',
    'financeiro.cartao.status.inativo': 'INATIVO',
    'financeiro.cartao.acoes.fatura': 'Fatura',
    'financeiro.cartao.acoes.ativar': 'Ativar',
    'financeiro.cartao.acoes.inativar': 'Inativar',
    'financeiro.cartao.faturaTitulo': 'Fatura do Cartão',
    'financeiro.cartao.faturaVazia': 'Nenhum lançamento encontrado para o mes selecionado.',
    'financeiro.cartao.totalFatura': 'Total da Fatura',
    'financeiro.cartao.mensagens.obrigatorio': 'Descrição, bandeira, tipo, limite, saldo disponível e datas são obrigatórios.',
    'financeiro.cartao.mensagens.obrigatorioCredito': 'Descrição, bandeira, tipo, limite, saldo disponível e datas são obrigatórios para cartão de crédito.',
    'financeiro.cartao.mensagens.obrigatorioDebito': 'Descrição, bandeira, tipo e saldo disponível são obrigatórios para cartão de débito.',
    'financeiro.cartao.mensagens.criado': 'Cartão criado com sucesso.',
    'financeiro.cartao.mensagens.atualizado': 'Cartão atualizado com sucesso.',
    'financeiro.cartao.mensagens.transacoesPendentes': 'Não ? possível inativar. Existem transações pendentes vinculadas a este cartão.',
    'financeiro.cartao.mensagens.confirmarAtivacao': 'Deseja ativar este cartão?',
    'financeiro.cartao.mensagens.confirmarInativacao': 'Deseja inativar este cartão?',
    'financeiro.cartao.logs.titulo': 'Logs de alteracoes',
    'financeiro.cartao.logs.criado': 'Cartão criado com status ativo.',
    'financeiro.cartao.logs.atualizado': 'Dados do cartão foram atualizados.',
    'financeiro.cartao.logs.ativado': 'Cartão ativado.',
    'financeiro.cartao.logs.inativado': 'Cartão inativado.',
    'financeiro.despesa.titulo': 'Despesas',
    'financeiro.despesa.nova': 'Nova Despesa',
    'financeiro.despesa.vazio': 'Nenhuma despesa encontrada.',
    'financeiro.despesa.campos.descricao': 'Descrição *',
    'financeiro.despesa.campos.observacao': 'Observacao',
    'financeiro.despesa.campos.dataLancamento': 'Data Lancamento *',
    'financeiro.despesa.campos.dataVencimento': 'Data Vencimento *',
    'financeiro.despesa.campos.dataEfetivacao': 'Data Efetivacao *',
    'financeiro.despesa.campos.tipoDespesa': 'Tipo de Despesa *',
    'financeiro.despesa.campos.tipoPagamento': 'Tipo de Pagamento *',
    'financeiro.despesa.campos.recorrencia': 'Recorrencia',
    'financeiro.despesa.campos.valorTotal': 'Valor Total *',
    'financeiro.despesa.campos.valorLiquido': 'Valor Liquido',
    'financeiro.despesa.campos.valorEfetivacao': 'Valor Efetivacao',
    'financeiro.despesa.campos.desconto': 'Desconto',
    'financeiro.despesa.campos.acrescimo': 'Acrescimo',
    'financeiro.despesa.campos.imposto': 'Imposto',
    'financeiro.despesa.campos.juros': 'Juros',
    'financeiro.despesa.campos.rateioAmigos': 'Rateio com amigos',
    'financeiro.despesa.campos.rateioTipoDespesa': 'Rateio por tipo de despesa',
    'financeiro.despesa.campos.anexoDocumento': 'Anexo de documento',
    'financeiro.despesa.campos.status': 'Status',
    'financeiro.despesa.placeholders.descricao': 'Digite a descrição da despesa',
    'financeiro.despesa.placeholders.observacao': 'Digite observacoes adicionais',
    'financeiro.despesa.placeholders.data': 'DD/MM/AAAA',
    'financeiro.despesa.placeholders.valor': '0,00',
    'financeiro.despesa.placeholders.anexo': 'Nome do arquivo ou documento',
    'financeiro.despesa.tipoDespesa.alimentacao': 'Alimentacao',
    'financeiro.despesa.tipoDespesa.transporte': 'Transporte',
    'financeiro.despesa.tipoDespesa.moradia': 'Moradia',
    'financeiro.despesa.tipoDespesa.lazer': 'Lazer',
    'financeiro.despesa.tipoDespesa.saude': 'Saude',
    'financeiro.despesa.tipoDespesa.educacao': 'Educacao',
    'financeiro.despesa.tipoDespesa.servicos': 'Servicos',
    'financeiro.despesa.tipoPagamento.pix': 'PIX',
    'financeiro.despesa.tipoPagamento.cartaoCredito': 'Cartão de Crédito',
    'financeiro.despesa.tipoPagamento.cartaoDebito': 'Cartão de Débito',
    'financeiro.despesa.tipoPagamento.boleto': 'Boleto',
    'financeiro.despesa.tipoPagamento.transferencia': 'Transferencia',
    'financeiro.despesa.tipoPagamento.dinheiro': 'Dinheiro',
    'financeiro.despesa.recorrencia.unica': 'Unica',
    'financeiro.despesa.recorrencia.semanal': 'Semanal',
    'financeiro.despesa.recorrencia.mensal': 'Mensal',
    'financeiro.despesa.recorrencia.anual': 'Anual',
    'financeiro.despesa.status.pendente': 'PENDENTE',
    'financeiro.despesa.status.efetivada': 'EFETIVADA',
    'financeiro.despesa.status.cancelada': 'CANCELADA',
    'financeiro.despesa.acoes.visualizar': 'Visualizar',
    'financeiro.despesa.acoes.efetivar': 'Efetivar',
    'financeiro.despesa.acoes.confirmarEfetivacao': 'Confirmar efetivação',
    'financeiro.despesa.acoes.cancelarDespesa': 'Cancelar despesa',
    'financeiro.despesa.acoes.estornar': 'Estornar',
    'financeiro.despesa.mensagens.obrigatorio': 'Descrição, datas, tipo de despesa e tipo de pagamento são obrigatórios.',
    'financeiro.despesa.mensagens.valorObrigatorio': 'Informe o valor total da despesa.',
    'financeiro.despesa.mensagens.obrigatorioEfetivacao': 'Data de efetivação, tipo de pagamento e valores são obrigatórios.',
    'financeiro.despesa.mensagens.dataVencimentoMaiorQueLancamento': 'A data de vencimento não pode ser menor que a data de lançamento.',
    'financeiro.despesa.mensagens.dataEfetivacaoMaiorQueLancamento': 'A data de efetivação não pode ser menor que a data de lançamento.',
    'financeiro.despesa.mensagens.edicaoSomentePendente': 'A despesa so pode ser editada enquanto estiver pendente.',
    'financeiro.despesa.mensagens.efetivacaoSomentePendente': 'Apenas despesas pendentes podem ser efetivadas.',
    'financeiro.despesa.mensagens.cancelamentoSomentePendente': 'Apenas despesas pendentes podem ser canceladas.',
    'financeiro.despesa.mensagens.estornoSomenteEfetivada': 'Apenas despesas efetivadas podem ser estornadas.',
    'financeiro.despesa.mensagens.confirmarCancelamento': 'Deseja cancelar esta despesa?',
    'financeiro.despesa.mensagens.criada': 'Despesa criada com sucesso.',
    'financeiro.despesa.mensagens.atualizada': 'Despesa atualizada com sucesso.',
    'financeiro.despesa.mensagens.efetivada': 'Despesa efetivada com sucesso.',
    'financeiro.despesa.mensagens.semObservacao': 'Sem observacao',
    'financeiro.despesa.logs.titulo': 'Logs de alteracoes',
    'financeiro.despesa.logs.criada': 'Despesa criada com status pendente.',
    'financeiro.despesa.logs.editada': 'Despesa editada enquanto pendente.',
    'financeiro.despesa.logs.efetivada': 'Despesa efetivada com valor liquido calculado.',
    'financeiro.despesa.logs.cancelada': 'Despesa cancelada ainda em status pendente.',
    'financeiro.despesa.logs.estornada': 'Despesa estornada e retornada para pendente.',
    'financeiro.comum.campos.subarea': 'Subárea',
    'financeiro.comum.campos.modoRecorrencia': 'Modo da recorrencia',
    'financeiro.comum.campos.quantidadeRecorrencia': 'Quantidade de recorrencias',
    'financeiro.comum.campos.quantidadeParcelas': 'Quantidade de parcelas',
    'financeiro.comum.opcoesRecorrencia.normal': 'Normal',
    'financeiro.comum.opcoesRecorrencia.fixa': 'Fixa',
    'financeiro.comum.mensagens.quantidadeRecorrenciaMaiorQueZero': 'Informe uma quantidade de recorrencias maior que zero.',
    'financeiro.comum.mensagens.limiteRecorrenciaNormal': 'A recorrencia normal permite no maximo {limite} ocorrencias.',
    'financeiro.comum.mensagens.primeiraOcorrenciaGerada': 'Primeira ocorrencia criada. As demais estao sendo geradas.',
    'financeiro.comum.mensagens.rateioDeveBaterValorTotal': 'A soma do rateio deve ser igual ao valor total.',
    'financeiro.receita.titulo': 'Receitas',
    'financeiro.receita.nova': 'Nova Receita',
    'financeiro.receita.vazio': 'Nenhuma receita encontrada.',
    'financeiro.receita.campos.descricao': 'Descrição *',
    'financeiro.receita.campos.observacao': 'Observacao',
    'financeiro.receita.campos.dataLancamento': 'Data Lancamento *',
    'financeiro.receita.campos.dataVencimento': 'Data Vencimento *',
    'financeiro.receita.campos.dataEfetivacao': 'Data Efetivacao *',
    'financeiro.receita.campos.tipoReceita': 'Tipo de Receita *',
    'financeiro.receita.campos.tipoRecebimento': 'Tipo de Recebimento *',
    'financeiro.receita.campos.contaBancaria': 'Conta Bancária',
    'financeiro.receita.campos.recorrencia': 'Recorrencia',
    'financeiro.receita.campos.valorTotal': 'Valor Total *',
    'financeiro.receita.campos.valorLiquido': 'Valor Liquido',
    'financeiro.receita.campos.valorEfetivacao': 'Valor Efetivacao',
    'financeiro.receita.campos.desconto': 'Desconto',
    'financeiro.receita.campos.acrescimo': 'Acrescimo',
    'financeiro.receita.campos.imposto': 'Imposto',
    'financeiro.receita.campos.juros': 'Juros',
    'financeiro.receita.campos.rateioAmigos': 'Rateio com amigos',
    'financeiro.receita.campos.rateioAmigosValores': 'Valores rateados por amigo',
    'financeiro.receita.campos.rateioAreaSubarea': 'Rateio por área e subárea',
    'financeiro.receita.campos.rateioAreaSubareaValores': 'Valores rateados por área e subárea',
    'financeiro.receita.campos.anexoDocumento': 'Anexo de documento',
    'financeiro.receita.campos.status': 'Status',
    'financeiro.receita.placeholders.descricao': 'Digite a descrição da receita',
    'financeiro.receita.placeholders.observacao': 'Digite observacoes adicionais',
    'financeiro.receita.placeholders.data': 'DD/MM/AAAA',
    'financeiro.receita.placeholders.valor': '0,00',
    'financeiro.receita.placeholders.anexo': 'Selecione um arquivo',
    'financeiro.receita.tipoReceita.salario': 'Salario',
    'financeiro.receita.tipoReceita.freelance': 'Freelance',
    'financeiro.receita.tipoReceita.reembolso': 'Reembolso',
    'financeiro.receita.tipoReceita.investimento': 'Investimento',
    'financeiro.receita.tipoReceita.bonus': 'Bonus',
    'financeiro.receita.tipoReceita.outros': 'Outros',
    'financeiro.receita.tipoRecebimento.pix': 'PIX',
    'financeiro.receita.tipoRecebimento.transferencia': 'Transferencia',
    'financeiro.receita.tipoRecebimento.contaCorrente': 'Conta Corrente',
    'financeiro.receita.tipoRecebimento.cartaoCredito': 'Cartao de Credito',
    'financeiro.receita.tipoRecebimento.cartaoDebito': 'Cartao de Debito',
    'financeiro.receita.tipoRecebimento.dinheiro': 'Dinheiro',
    'financeiro.receita.tipoRecebimento.boleto': 'Boleto',
    'financeiro.receita.recorrencia.unica': 'Unica',
    'financeiro.receita.recorrencia.semanal': 'Semanal',
    'financeiro.receita.recorrencia.mensal': 'Mensal',
    'financeiro.receita.recorrencia.anual': 'Anual',
    'financeiro.receita.status.pendente': 'PENDENTE',
    'financeiro.receita.status.efetivada': 'EFETIVADA',
    'financeiro.receita.status.cancelada': 'CANCELADA',
    'financeiro.receita.acoes.visualizar': 'Visualizar',
    'financeiro.receita.acoes.efetivar': 'Efetivar',
    'financeiro.receita.acoes.confirmarEfetivacao': 'Confirmar efetivação',
    'financeiro.receita.acoes.cancelarReceita': 'Cancelar receita',
    'financeiro.receita.acoes.estornar': 'Estornar',
    'financeiro.receita.mensagens.obrigatorio': 'Descrição, datas, tipo de receita e tipo de recebimento são obrigatórios.',
    'financeiro.receita.mensagens.valorObrigatorio': 'Informe o valor total da receita.',
    'financeiro.receita.mensagens.contaObrigatoria': 'Selecione a conta bancária para este recebimento.',
    'financeiro.receita.mensagens.obrigatorioEfetivacao': 'Data de efetivação, tipo de recebimento e valores são obrigatórios.',
    'financeiro.receita.mensagens.dataVencimentoMaiorQueLancamento': 'A data de vencimento não pode ser menor que a data de lançamento.',
    'financeiro.receita.mensagens.dataEfetivacaoMaiorQueLancamento': 'A data de efetivação não pode ser menor que a data de lançamento.',
    'financeiro.receita.mensagens.edicaoSomentePendente': 'A receita so pode ser editada enquanto estiver pendente.',
    'financeiro.receita.mensagens.efetivacaoSomentePendente': 'Apenas receitas pendentes podem ser efetivadas.',
    'financeiro.receita.mensagens.cancelamentoSomentePendente': 'Apenas receitas pendentes podem ser canceladas.',
    'financeiro.receita.mensagens.estornoSomenteEfetivada': 'Apenas receitas efetivadas podem ser estornadas.',
    'financeiro.receita.mensagens.confirmarCancelamento': 'Deseja cancelar esta receita?',
    'financeiro.receita.mensagens.criada': 'Receita criada com sucesso.',
    'financeiro.receita.mensagens.atualizada': 'Receita atualizada com sucesso.',
    'financeiro.receita.mensagens.efetivada': 'Receita efetivada com sucesso.',
    'financeiro.receita.mensagens.semObservacao': 'Sem observacao',
    'financeiro.receita.logs.titulo': 'Logs de alteracoes',
    'financeiro.receita.logs.criada': 'Receita criada com status pendente.',
    'financeiro.receita.logs.editada': 'Receita editada enquanto pendente.',
    'financeiro.receita.logs.efetivada': 'Receita efetivada com valor liquido calculado.',
    'financeiro.receita.logs.cancelada': 'Receita cancelada ainda em status pendente.',
    'financeiro.receita.logs.estornada': 'Receita estornada e retornada para pendente.',
    'financeiro.contaBancaria.titulo': 'Contas Bancárias',
    'financeiro.contaBancaria.nova': 'Nova Conta Bancária',
    'financeiro.contaBancaria.vazio': 'Nenhuma conta bancária encontrada.',
    'financeiro.contaBancaria.campos.descricao': 'Descrição *',
    'financeiro.contaBancaria.campos.banco': 'Banco *',
    'financeiro.contaBancaria.campos.agencia': 'Agência *',
    'financeiro.contaBancaria.campos.numero': 'Número *',
    'financeiro.contaBancaria.campos.saldoInicial': 'Saldo Inicial *',
    'financeiro.contaBancaria.campos.saldoAtual': 'Saldo Atual',
    'financeiro.contaBancaria.campos.dataAbertura': 'Data de Abertura *',
    'financeiro.contaBancaria.campos.status': 'Status',
    'financeiro.contaBancaria.placeholders.descricao': 'Digite a descrição da conta',
    'financeiro.contaBancaria.placeholders.agencia': 'Digite a agência',
    'financeiro.contaBancaria.placeholders.numero': 'Digite o número da conta',
    'financeiro.contaBancaria.placeholders.saldoInicial': '0,00',
    'financeiro.contaBancaria.placeholders.dataAbertura': 'DD/MM/AAAA',
    'financeiro.contaBancaria.status.ativa': 'ATIVA',
    'financeiro.contaBancaria.status.inativa': 'INATIVA',
    'financeiro.contaBancaria.acoes.ativar': 'Ativar',
    'financeiro.contaBancaria.acoes.inativar': 'Inativar',
    'financeiro.contaBancaria.acoes.extrato': 'Extrato',
    'financeiro.contaBancaria.extratoTitulo': 'Extrato da Conta',
    'financeiro.contaBancaria.extratoVazio': 'Nenhum movimento encontrado.',
    'financeiro.contaBancaria.tipos.credito': 'Crédito',
    'financeiro.contaBancaria.tipos.debito': 'Débito',
    'financeiro.contaBancaria.mensagens.obrigatorio': 'Descrição, banco, agência, número, saldo inicial e data de abertura são obrigatórios.',
    'financeiro.contaBancaria.mensagens.saldoObrigatorio': 'Informe o saldo inicial.',
    'financeiro.contaBancaria.mensagens.criada': 'Conta bancária criada com sucesso.',
    'financeiro.contaBancaria.mensagens.atualizada': 'Conta bancária atualizada com sucesso.',
    'financeiro.contaBancaria.mensagens.transacoesPendentes': 'Não ? possível inativar a conta porque existem transações pendentes vinculadas.',
    'financeiro.contaBancaria.mensagens.confirmarAtivacao': 'Deseja ativar esta conta bancária?',
    'financeiro.contaBancaria.mensagens.confirmarInativacao': 'Deseja inativar esta conta bancária?',
    'financeiro.contaBancaria.logs.titulo': 'Logs de alteracoes',
    'financeiro.contaBancaria.logs.criada': 'Conta bancária criada com status ativa.',
    'financeiro.contaBancaria.logs.atualizada': 'Conta bancária atualizada.',
    'financeiro.contaBancaria.logs.ativada': 'Conta bancária ativada.',
    'financeiro.contaBancaria.logs.inativada': 'Conta bancária inativada.',
  },
  en: {
    'comum.email': 'Email',
    'comum.senha': 'Password',
    'comum.entrar': 'Login',
    'comum.sair': 'Logout',
    'menu.painelUsuario': 'User Panel',
    'comum.erro': 'Error',
    'comum.sucesso': 'Success',
    'comum.carregando': 'Loading',
    'comum.acoes.selecionar': 'Select',
    'comum.acoes.visualizar': 'View',
    'comum.acoes.editar': 'Edit',
    'comum.acoes.cancelar': 'Cancel',
    'comum.acoes.salvar': 'Save',
    'comum.acoes.confirmar': 'Confirm',
    'comum.acoes.remover': 'Remove',
    'dashboard.titulo': 'Dashboard',
    'dashboard.bem-vindo': 'Welcome to Core!',
    'dashboard.saudacao-usuario': 'Hello, {{nome}}! You are logged in as {{perfil}}.',
    'dashboard.informacoes': 'User Information',
    'dashboard.modulos': 'Active Modules',
    'dashboard.nenhum-modulo': 'None',
    'dashboard.proximos-passos': 'Next steps: Implement finance module',
    'dashboard.globalTitle': 'Financial Overview',
    'dashboard.globalDescription': 'Track the main financial indicators, recent movements, yearly performance, and the consolidated balance of accounts and cards.',
    'dashboard.resumoFinanceiro': 'Financial Summary',
    'dashboard.graficoAreaSubarea': 'Chart by Area and Subarea',
    'dashboard.graficoAreaSubareaDescricao': 'Income and expenses consolidated by area and subarea for the selected period.',
    'dashboard.graficoAreaSubareaCentro': 'Filtered Total',
    'dashboard.graficoAnual': 'Yearly Chart',
    'dashboard.ultimasTransacoes': 'Latest Transactions',
    'dashboard.balancoGeral': 'Overall Balance',
    'dashboard.saldoAtualConta': 'Current Account Balance',
    'dashboard.saldoDisponivelCartao': 'Available Card Balance',
    'dashboard.widget': 'Widget',
    'dashboard.reordenarHint': 'Drag the widgets or use the arrows to reorder the dashboard.',
    'dashboard.widgetGraficoInfo': 'Values follow the selected language and reflect the applied filters.',
    'dashboard.cards.receitas': 'Income',
    'dashboard.cards.despesas': 'Expenses',
    'dashboard.cards.reembolsos': 'Reimbursements',
    'dashboard.cards.estornos': 'Reversals',
    'dashboard.cards.saldo': 'Balance',
    'dashboard.widgets.resumo': 'Financial Summary',
    'dashboard.widgets.graficoAreaSubarea': 'Chart by Area and Subarea',
    'dashboard.widgets.graficoAnual': 'Yearly Chart',
    'dashboard.widgets.ultimasTransacoes': 'Latest Transactions',
    'dashboard.widgets.balancoGeral': 'Overall Balance',
    'dashboard.colunas.id': 'ID',
    'dashboard.colunas.tipo': 'Type',
    'dashboard.colunas.valor': 'Amount',
    'dashboard.colunas.descricao': 'Description',
    'dashboard.colunas.dataEfetivacao': 'Date',
    'dashboard.colunas.tipoPagamento': 'Payment / Receipt',
    'dashboard.colunas.contaBancaria': 'Bank Account',
    'dashboard.colunas.cartao': 'Card',
    'dashboard.colunas.areaSubarea': 'Area / Subarea',
    'dashboard.tipos.despesa': 'Expense',
    'dashboard.tipos.receita': 'Income',
    'dashboard.tipos.reembolso': 'Reimbursement',
    'dashboard.tipos.estorno': 'Reversal',
    'dashboard.tiposBalanco.conta': 'Bank Account',
    'dashboard.tiposBalanco.cartao': 'Card',
    'dashboard.pagamento.PIX': 'PIX',
    'dashboard.pagamento.TRANSFERENCIA': 'Transfer',
    'dashboard.pagamento.CARTAO_CREDITO': 'Credit Card',
    'dashboard.pagamento.BOLETO': 'Bank Slip',
    'dashboard.pagamento.DINHEIRO': 'Cash',
    'dashboard.contas.BANCO_XP': 'XP Bank',
    'dashboard.contas.BANCO_DIGITAL': 'Digital Bank',
    'dashboard.contas.ITAU': 'Ita?',
    'dashboard.contas.NUBANK': 'Nubank',
    'dashboard.contas.INTER': 'Inter',
    'dashboard.descricoes.ALMOCO_CLIENTE': 'Client lunch',
    'dashboard.descricoes.VENDA_SERVICO': 'Service sale',
    'dashboard.descricoes.REEMBOLSO_VIAGEM': 'Travel reimbursement',
    'dashboard.descricoes.ESTORNO_COBRANCA': 'Charge reversal',
    'dashboard.descricoes.ASSINATURA': 'Monthly subscription',
    'dashboard.descricoes.SUPERMERCADO': 'Grocery purchase',
    'dashboard.descricoes.COMBUSTIVEL': 'Fuel',
    'dashboard.descricoes.RECEBIMENTO': 'Recurring receipt',
    'dashboard.areas.OPERACOES': 'Operations',
    'dashboard.areas.COMERCIAL': 'Commercial',
    'dashboard.areas.PESSOAL': 'People',
    'dashboard.areas.LAZER': 'Leisure',
    'dashboard.areas.TECNOLOGIA': 'Technology',
    'dashboard.areas.FINANCEIRO': 'Finance',
    'dashboard.areas.LOGISTICA': 'Logistics',
    'dashboard.areas.JURIDICO': 'Legal',
    'dashboard.areas.ADMINISTRATIVO': 'Administrative',
    'dashboard.areas.ATENDIMENTO': 'Customer Service',
    'dashboard.subareas.SUPRIMENTOS': 'Supplies',
    'dashboard.subareas.TRANSPORTE': 'Transport',
    'dashboard.subareas.MANUTENCAO': 'Maintenance',
    'dashboard.subareas.VENDAS': 'Sales',
    'dashboard.subareas.MARKETING': 'Marketing',
    'dashboard.subareas.EVENTOS': 'Events',
    'dashboard.subareas.SALARIOS': 'Payroll',
    'dashboard.subareas.BENEFICIOS': 'Benefits',
    'dashboard.subareas.TREINAMENTO': 'Training',
    'dashboard.subareas.VIAGENS': 'Trips',
    'dashboard.subareas.CINEMA': 'Cinema',
    'dashboard.subareas.RESTAURANTES': 'Restaurants',
    'dashboard.subareas.SOFTWARE': 'Software',
    'dashboard.subareas.INFRAESTRUTURA': 'Infrastructure',
    'dashboard.subareas.LICENCAS': 'Licenses',
    'dashboard.subareas.IMPOSTOS': 'Taxes',
    'dashboard.subareas.TARIFAS': 'Fees',
    'dashboard.subareas.INVESTIMENTOS': 'Investments',
    'dashboard.subareas.ARMAZENAGEM': 'Warehousing',
    'dashboard.subareas.FRETES': 'Freight',
    'dashboard.subareas.DISTRIBUICAO': 'Distribution',
    'dashboard.subareas.CONTRATOS': 'Contracts',
    'dashboard.subareas.CONSULTORIA': 'Consulting',
    'dashboard.subareas.PROCESSOS': 'Litigation',
    'dashboard.subareas.FACILITIES': 'Facilities',
    'dashboard.subareas.VIAGENS_CORPORATIVAS': 'Corporate Travel',
    'dashboard.subareas.PATRIMONIO': 'Assets',
    'dashboard.subareas.SUPORTE': 'Support',
    'dashboard.subareas.POS_VENDA': 'After Sales',
    'dashboard.subareas.OUVIDORIA': 'Ombudsman',

    'financeiro.despesas': 'Expenses',
    'financeiro.receitas': 'Income',
    'financeiro.reembolsos': 'Reimbursements',
    'amigos.titulo': 'Friends',
    'admin.titulo': 'Administration',
    'documentacao.titulo': 'Documentation - {{modulo}}',
    'documentacao.acao': 'Documentation',
    'documentacao.descricaoPadrao': 'This screen groups the published contents for the {{modulo}} module. The information is maintained by administration.',
    'documentacao.vazio': 'No published documentation for this module.',
    'documentacao.atualizadoEm': 'Updated on',
    'documentacao.modulos.dashboard': 'Dashboard',
    'documentacao.modulos.financeiro': 'Finance',
    'documentacao.modulos.amigos': 'Friends',
    'documentacao.modulos.admin': 'Administration',
    'comum.login.esqueciSenha': 'I forgot my password',
    'comum.login.esqueciSenhaSucesso': 'If the email is registered, recovery instructions will be sent.',
    'comum.login.credenciaisTeste': 'Use admin@core.com / 123456 for testing',
    'comum.login.tentativasRestantes': 'Remaining attempts: {{tentativas}}',
    'comum.login.erros.camposObrigatorios': 'Email and Password are required',
    'comum.login.erros.emailInvalido': 'Enter a valid email',
    'comum.login.erros.emailObrigatorioRecuperacao': 'Enter the email to recover the password',
    'comum.login.erros.credenciaisInvalidas': 'Invalid credentials. Remaining attempts: {{tentativas}}',
    'comum.login.erros.bloqueadoTentativas': 'Login blocked after 5 invalid attempts.',
    'primeiroAcesso.titulo': 'Create your access password',
    'primeiroAcesso.descricao': 'On first login, it is mandatory to set a new password.',
    'primeiroAcesso.campos.novaSenha': 'New password *',
    'primeiroAcesso.campos.confirmarSenha': 'Confirm new password *',
    'primeiroAcesso.botaoConfirmar': 'Confirm password',
    'primeiroAcesso.sucesso.senhaCriada': 'Password created successfully.',
    'primeiroAcesso.erros.camposObrigatorios': 'Fill both password fields.',
    'primeiroAcesso.erros.senhaMinima': 'Password must be at least 10 characters.',
    'primeiroAcesso.erros.confirmacaoDiferente': 'Password confirmation does not match.',
    'primeiroAcesso.erros.falhaCriarSenha': 'Could not create password.',
    'usuarioPainel.titulo': 'User Panel',
    'usuarioPainel.informacoes': 'User Information',
    'usuarioPainel.nome': 'Name',
    'usuarioPainel.email': 'Email',
    'usuarioPainel.perfil': 'Access Profile',
    'usuarioPainel.alterarSenha': 'Change Password',
    'usuarioPainel.campos.senhaAtual': 'Current Password *',
    'usuarioPainel.campos.novaSenha': 'New Password *',
    'usuarioPainel.campos.confirmarSenha': 'Confirm New Password *',
    'usuarioPainel.botaoSalvar': 'Save New Password',
    'usuarioPainel.sucesso.senhaAlterada': 'Password changed successfully.',
    'usuarioPainel.erros.camposObrigatorios': 'Fill all password fields.',
    'usuarioPainel.erros.senhaMinima': 'The new password must be at least 10 characters.',
    'usuarioPainel.erros.confirmacaoDiferente': 'Password confirmation does not match.',
    'usuarioPainel.erros.falhaAlterarSenha': 'Could not change password.',
    'admin.documentacao.gerenciar': 'Manage Documentation',
    'admin.documentacao.novo': 'New Documentation',
    'admin.documentacao.editar': 'Edit Documentation',
    'admin.documentacao.modulo': 'Module',
    'admin.documentacao.titulo': 'Title',
    'admin.documentacao.resumo': 'Summary',
    'admin.documentacao.conteudo': 'Content',
    'admin.documentacao.placeholderTitulo': 'Enter the documentation title',
    'admin.documentacao.placeholderResumo': 'Briefly describe the purpose of this content',
    'admin.documentacao.placeholderConteudo': 'Explain features, rules and flows for the module',
    'admin.documentacao.salvoSucesso': 'Documentation saved successfully.',
    'admin.documentacao.publicadoSucesso': 'Documentation published successfully.',
    'admin.documentacao.deletadoSucesso': 'Documentation removed successfully.',
    'admin.documentacao.confirmarDelete': 'Do you want to remove this documentation?',
    'admin.documentacao.erros.camposObrigatorios': 'Title, summary and content are required.',
    'financeiro.cartao.acoes.extrato': 'Statement',
    'financeiro.cartao.extratoTitulo': 'Spending Statement',
    'financeiro.cartao.extratoVazio': 'No spending found for the selected month.',
    'financeiro.cartao.totalExtrato': 'Statement Total',
    'financeiro.cartao.titulo': 'Cards',
    'financeiro.cartao.novo': 'New Card',
    'financeiro.cartao.vazio': 'No cards found.',
    'financeiro.cartao.campos.descricao': 'Description *',
    'financeiro.cartao.campos.bandeira': 'Brand *',
    'financeiro.cartao.campos.tipo': 'Type *',
    'financeiro.cartao.campos.limite': 'Limit *',
    'financeiro.cartao.campos.saldoDisponivel': 'Available Balance *',
    'financeiro.cartao.campos.diaVencimento': 'Due Day *',
    'financeiro.cartao.campos.dataVencimentoCartao': 'Card Due Date *',
    'financeiro.cartao.campos.status': 'Status',
    'financeiro.cartao.placeholders.descricao': 'Enter the card description',
    'financeiro.cartao.placeholders.valor': '0.00',
    'financeiro.cartao.placeholders.data': 'MM/DD/YYYY',
    'financeiro.cartao.tipos.credito': 'Credit',
    'financeiro.cartao.tipos.debito': 'Debit',
    'financeiro.cartao.status.ativo': 'ACTIVE',
    'financeiro.cartao.status.inativo': 'INACTIVE',
    'financeiro.cartao.acoes.fatura': 'Invoice',
    'financeiro.cartao.acoes.ativar': 'Activate',
    'financeiro.cartao.acoes.inativar': 'Deactivate',
    'financeiro.cartao.faturaTitulo': 'Card Invoice',
    'financeiro.cartao.faturaVazia': 'No transactions found for the selected month.',
    'financeiro.cartao.totalFatura': 'Invoice Total',
    'financeiro.cartao.mensagens.obrigatorio': 'Description, brand, type, limit, available balance and dates are required.',
    'financeiro.cartao.mensagens.obrigatorioCredito': 'Description, brand, type, limit, available balance and dates are required for credit cards.',
    'financeiro.cartao.mensagens.obrigatorioDebito': 'Description, brand, type and available balance are required for debit cards.',
    'financeiro.cartao.mensagens.criado': 'Card created successfully.',
    'financeiro.cartao.mensagens.atualizado': 'Card updated successfully.',
    'financeiro.cartao.mensagens.transacoesPendentes': 'Cannot deactivate. There are pending transactions linked to this card.',
    'financeiro.cartao.mensagens.confirmarAtivacao': 'Do you want to activate this card?',
    'financeiro.cartao.mensagens.confirmarInativacao': 'Do you want to deactivate this card?',
    'financeiro.cartao.logs.titulo': 'Change logs',
    'financeiro.cartao.logs.criado': 'Card created with active status.',
    'financeiro.cartao.logs.atualizado': 'Card data was updated.',
    'financeiro.cartao.logs.ativado': 'Card activated.',
    'financeiro.cartao.logs.inativado': 'Card deactivated.',
    'financeiro.despesa.titulo': 'Expenses',
    'financeiro.despesa.nova': 'New Expense',
    'financeiro.despesa.vazio': 'No expenses found.',
    'financeiro.despesa.campos.descricao': 'Description *',
    'financeiro.despesa.campos.observacao': 'Notes',
    'financeiro.despesa.campos.dataLancamento': 'Posting Date *',
    'financeiro.despesa.campos.dataVencimento': 'Due Date *',
    'financeiro.despesa.campos.dataEfetivacao': 'Settlement Date *',
    'financeiro.despesa.campos.tipoDespesa': 'Expense Type *',
    'financeiro.despesa.campos.tipoPagamento': 'Payment Type *',
    'financeiro.despesa.campos.recorrencia': 'Recurrence',
    'financeiro.despesa.campos.valorTotal': 'Gross Amount *',
    'financeiro.despesa.campos.valorLiquido': 'Net Amount',
    'financeiro.despesa.campos.valorEfetivacao': 'Settlement Amount',
    'financeiro.despesa.campos.desconto': 'Discount',
    'financeiro.despesa.campos.acrescimo': 'Additional Charge',
    'financeiro.despesa.campos.imposto': 'Tax',
    'financeiro.despesa.campos.juros': 'Interest',
    'financeiro.despesa.campos.rateioAmigos': 'Split with friends',
    'financeiro.despesa.campos.rateioTipoDespesa': 'Split by expense type',
    'financeiro.despesa.campos.anexoDocumento': 'Document attachment',
    'financeiro.despesa.campos.status': 'Status',
    'financeiro.despesa.placeholders.descricao': 'Enter expense description',
    'financeiro.despesa.placeholders.observacao': 'Enter additional notes',
    'financeiro.despesa.placeholders.data': 'MM/DD/YYYY',
    'financeiro.despesa.placeholders.valor': '0.00',
    'financeiro.despesa.placeholders.anexo': 'File or document name',
    'financeiro.despesa.tipoDespesa.alimentacao': 'Food',
    'financeiro.despesa.tipoDespesa.transporte': 'Transport',
    'financeiro.despesa.tipoDespesa.moradia': 'Housing',
    'financeiro.despesa.tipoDespesa.lazer': 'Leisure',
    'financeiro.despesa.tipoDespesa.saude': 'Health',
    'financeiro.despesa.tipoDespesa.educacao': 'Education',
    'financeiro.despesa.tipoDespesa.servicos': 'Services',
    'financeiro.despesa.tipoPagamento.pix': 'PIX',
    'financeiro.despesa.tipoPagamento.cartaoCredito': 'Credit Card',
    'financeiro.despesa.tipoPagamento.cartaoDebito': 'Debit Card',
    'financeiro.despesa.tipoPagamento.boleto': 'Bank Slip',
    'financeiro.despesa.tipoPagamento.transferencia': 'Transfer',
    'financeiro.despesa.tipoPagamento.dinheiro': 'Cash',
    'financeiro.despesa.recorrencia.unica': 'One-time',
    'financeiro.despesa.recorrencia.semanal': 'Weekly',
    'financeiro.despesa.recorrencia.mensal': 'Monthly',
    'financeiro.despesa.recorrencia.anual': 'Yearly',
    'financeiro.despesa.status.pendente': 'PENDING',
    'financeiro.despesa.status.efetivada': 'SETTLED',
    'financeiro.despesa.status.cancelada': 'CANCELED',
    'financeiro.despesa.acoes.visualizar': 'View',
    'financeiro.despesa.acoes.efetivar': 'Settle',
    'financeiro.despesa.acoes.confirmarEfetivacao': 'Confirm settlement',
    'financeiro.despesa.acoes.cancelarDespesa': 'Cancel expense',
    'financeiro.despesa.acoes.estornar': 'Reverse',
    'financeiro.despesa.mensagens.obrigatorio': 'Description, dates, expense type and payment type are required.',
    'financeiro.despesa.mensagens.valorObrigatorio': 'Enter the gross amount.',
    'financeiro.despesa.mensagens.obrigatorioEfetivacao': 'Settlement date, payment type and amounts are required.',
    'financeiro.despesa.mensagens.dataVencimentoMaiorQueLancamento': 'Due date cannot be less than launch date.',
    'financeiro.despesa.mensagens.dataEfetivacaoMaiorQueLancamento': 'Settlement date cannot be less than launch date.',
    'financeiro.despesa.mensagens.edicaoSomentePendente': 'The expense can only be edited while pending.',
    'financeiro.despesa.mensagens.efetivacaoSomentePendente': 'Only pending expenses can be settled.',
    'financeiro.despesa.mensagens.cancelamentoSomentePendente': 'Only pending expenses can be canceled.',
    'financeiro.despesa.mensagens.estornoSomenteEfetivada': 'Only settled expenses can be reversed.',
    'financeiro.despesa.mensagens.confirmarCancelamento': 'Do you want to cancel this expense?',
    'financeiro.despesa.mensagens.criada': 'Expense created successfully.',
    'financeiro.despesa.mensagens.atualizada': 'Expense updated successfully.',
    'financeiro.despesa.mensagens.efetivada': 'Expense settled successfully.',
    'financeiro.despesa.mensagens.semObservacao': 'No notes',
    'financeiro.despesa.logs.titulo': 'Change logs',
    'financeiro.despesa.logs.criada': 'Expense created with pending status.',
    'financeiro.despesa.logs.editada': 'Expense edited while pending.',
    'financeiro.despesa.logs.efetivada': 'Expense settled with calculated net amount.',
    'financeiro.despesa.logs.cancelada': 'Expense canceled while still pending.',
    'financeiro.despesa.logs.estornada': 'Expense reversed and returned to pending.',
    'financeiro.comum.campos.subarea': 'Subarea',
    'financeiro.comum.campos.modoRecorrencia': 'Recurrence mode',
    'financeiro.comum.campos.quantidadeRecorrencia': 'Recurrence quantity',
    'financeiro.comum.campos.quantidadeParcelas': 'Installment quantity',
    'financeiro.comum.opcoesRecorrencia.normal': 'Normal',
    'financeiro.comum.opcoesRecorrencia.fixa': 'Fixed',
    'financeiro.comum.mensagens.quantidadeRecorrenciaMaiorQueZero': 'Enter a recurrence quantity greater than zero.',
    'financeiro.comum.mensagens.limiteRecorrenciaNormal': 'Normal recurrence allows up to {limite} occurrences.',
    'financeiro.comum.mensagens.primeiraOcorrenciaGerada': 'First occurrence created. The remaining ones are being generated.',
    'financeiro.comum.mensagens.rateioDeveBaterValorTotal': 'Split total must be equal to the total amount.',
    'financeiro.receita.titulo': 'Income',
    'financeiro.receita.nova': 'New Income',
    'financeiro.receita.vazio': 'No income found.',
    'financeiro.receita.campos.descricao': 'Description *',
    'financeiro.receita.campos.observacao': 'Notes',
    'financeiro.receita.campos.dataLancamento': 'Posting Date *',
    'financeiro.receita.campos.dataVencimento': 'Due Date *',
    'financeiro.receita.campos.dataEfetivacao': 'Settlement Date *',
    'financeiro.receita.campos.tipoReceita': 'Income Type *',
    'financeiro.receita.campos.tipoRecebimento': 'Receiving Type *',
    'financeiro.receita.campos.contaBancaria': 'Bank Account',
    'financeiro.receita.campos.recorrencia': 'Recurrence',
    'financeiro.receita.campos.valorTotal': 'Gross Amount *',
    'financeiro.receita.campos.valorLiquido': 'Net Amount',
    'financeiro.receita.campos.valorEfetivacao': 'Settlement Amount',
    'financeiro.receita.campos.desconto': 'Discount',
    'financeiro.receita.campos.acrescimo': 'Additional Charge',
    'financeiro.receita.campos.imposto': 'Tax',
    'financeiro.receita.campos.juros': 'Interest',
    'financeiro.receita.campos.rateioAmigos': 'Split with friends',
    'financeiro.receita.campos.rateioAmigosValores': 'Split values by friend',
    'financeiro.receita.campos.rateioAreaSubarea': 'Split by area and subarea',
    'financeiro.receita.campos.rateioAreaSubareaValores': 'Split values by area and subarea',
    'financeiro.receita.campos.anexoDocumento': 'Document attachment',
    'financeiro.receita.campos.status': 'Status',
    'financeiro.receita.placeholders.descricao': 'Enter income description',
    'financeiro.receita.placeholders.observacao': 'Enter additional notes',
    'financeiro.receita.placeholders.data': 'MM/DD/YYYY',
    'financeiro.receita.placeholders.valor': '0.00',
    'financeiro.receita.placeholders.anexo': 'Select a file',
    'financeiro.receita.tipoReceita.salario': 'Salary',
    'financeiro.receita.tipoReceita.freelance': 'Freelance',
    'financeiro.receita.tipoReceita.reembolso': 'Reimbursement',
    'financeiro.receita.tipoReceita.investimento': 'Investment',
    'financeiro.receita.tipoReceita.bonus': 'Bonus',
    'financeiro.receita.tipoReceita.outros': 'Other',
    'financeiro.receita.tipoRecebimento.pix': 'PIX',
    'financeiro.receita.tipoRecebimento.transferencia': 'Transfer',
    'financeiro.receita.tipoRecebimento.contaCorrente': 'Checking Account',
    'financeiro.receita.tipoRecebimento.cartaoCredito': 'Credit Card',
    'financeiro.receita.tipoRecebimento.cartaoDebito': 'Debit Card',
    'financeiro.receita.tipoRecebimento.dinheiro': 'Cash',
    'financeiro.receita.tipoRecebimento.boleto': 'Bank Slip',
    'financeiro.receita.recorrencia.unica': 'One-time',
    'financeiro.receita.recorrencia.semanal': 'Weekly',
    'financeiro.receita.recorrencia.mensal': 'Monthly',
    'financeiro.receita.recorrencia.anual': 'Yearly',
    'financeiro.receita.status.pendente': 'PENDING',
    'financeiro.receita.status.efetivada': 'SETTLED',
    'financeiro.receita.status.cancelada': 'CANCELED',
    'financeiro.receita.acoes.visualizar': 'View',
    'financeiro.receita.acoes.efetivar': 'Settle',
    'financeiro.receita.acoes.confirmarEfetivacao': 'Confirm settlement',
    'financeiro.receita.acoes.cancelarReceita': 'Cancel income',
    'financeiro.receita.acoes.estornar': 'Reverse',
    'financeiro.receita.mensagens.obrigatorio': 'Description, dates, income type and receiving type are required.',
    'financeiro.receita.mensagens.valorObrigatorio': 'Enter the gross amount.',
    'financeiro.receita.mensagens.contaObrigatoria': 'Select the bank account for this receiving type.',
    'financeiro.receita.mensagens.obrigatorioEfetivacao': 'Settlement date, receiving type and amounts are required.',
    'financeiro.receita.mensagens.dataVencimentoMaiorQueLancamento': 'Due date cannot be less than launch date.',
    'financeiro.receita.mensagens.dataEfetivacaoMaiorQueLancamento': 'Settlement date cannot be less than launch date.',
    'financeiro.receita.mensagens.edicaoSomentePendente': 'The income can only be edited while pending.',
    'financeiro.receita.mensagens.efetivacaoSomentePendente': 'Only pending income can be settled.',
    'financeiro.receita.mensagens.cancelamentoSomentePendente': 'Only pending income can be canceled.',
    'financeiro.receita.mensagens.estornoSomenteEfetivada': 'Only settled income can be reversed.',
    'financeiro.receita.mensagens.confirmarCancelamento': 'Do you want to cancel this income?',
    'financeiro.receita.mensagens.criada': 'Income created successfully.',
    'financeiro.receita.mensagens.atualizada': 'Income updated successfully.',
    'financeiro.receita.mensagens.efetivada': 'Income settled successfully.',
    'financeiro.receita.mensagens.semObservacao': 'No notes',
    'financeiro.receita.logs.titulo': 'Change logs',
    'financeiro.receita.logs.criada': 'Income created with pending status.',
    'financeiro.receita.logs.editada': 'Income edited while pending.',
    'financeiro.receita.logs.efetivada': 'Income settled with calculated net amount.',
    'financeiro.receita.logs.cancelada': 'Income canceled while still pending.',
    'financeiro.receita.logs.estornada': 'Income reversed and returned to pending.',
    'financeiro.contaBancaria.titulo': 'Bank Accounts',
    'financeiro.contaBancaria.nova': 'New Bank Account',
    'financeiro.contaBancaria.vazio': 'No bank accounts found.',
    'financeiro.contaBancaria.campos.descricao': 'Description *',
    'financeiro.contaBancaria.campos.banco': 'Bank *',
    'financeiro.contaBancaria.campos.agencia': 'Branch *',
    'financeiro.contaBancaria.campos.numero': 'Number *',
    'financeiro.contaBancaria.campos.saldoInicial': 'Initial Balance *',
    'financeiro.contaBancaria.campos.saldoAtual': 'Current Balance',
    'financeiro.contaBancaria.campos.dataAbertura': 'Opening Date *',
    'financeiro.contaBancaria.campos.status': 'Status',
    'financeiro.contaBancaria.placeholders.descricao': 'Enter account description',
    'financeiro.contaBancaria.placeholders.agencia': 'Enter branch',
    'financeiro.contaBancaria.placeholders.numero': 'Enter account number',
    'financeiro.contaBancaria.placeholders.saldoInicial': '0.00',
    'financeiro.contaBancaria.placeholders.dataAbertura': 'MM/DD/YYYY',
    'financeiro.contaBancaria.status.ativa': 'ACTIVE',
    'financeiro.contaBancaria.status.inativa': 'INACTIVE',
    'financeiro.contaBancaria.acoes.ativar': 'Activate',
    'financeiro.contaBancaria.acoes.inativar': 'Deactivate',
    'financeiro.contaBancaria.acoes.extrato': 'Statement',
    'financeiro.contaBancaria.extratoTitulo': 'Account Statement',
    'financeiro.contaBancaria.extratoVazio': 'No movements found.',
    'financeiro.contaBancaria.tipos.credito': 'Credit',
    'financeiro.contaBancaria.tipos.debito': 'Debit',
    'financeiro.contaBancaria.mensagens.obrigatorio': 'Description, bank, branch, number, initial balance and opening date are required.',
    'financeiro.contaBancaria.mensagens.saldoObrigatorio': 'Enter the initial balance.',
    'financeiro.contaBancaria.mensagens.criada': 'Bank account created successfully.',
    'financeiro.contaBancaria.mensagens.atualizada': 'Bank account updated successfully.',
    'financeiro.contaBancaria.mensagens.transacoesPendentes': 'The account cannot be deactivated because there are pending linked transactions.',
    'financeiro.contaBancaria.mensagens.confirmarAtivacao': 'Do you want to activate this bank account?',
    'financeiro.contaBancaria.mensagens.confirmarInativacao': 'Do you want to deactivate this bank account?',
    'financeiro.contaBancaria.logs.titulo': 'Change logs',
    'financeiro.contaBancaria.logs.criada': 'Bank account created with active status.',
    'financeiro.contaBancaria.logs.atualizada': 'Bank account updated.',
    'financeiro.contaBancaria.logs.ativada': 'Bank account activated.',
    'financeiro.contaBancaria.logs.inativada': 'Bank account deactivated.',
  },
  es: {
    'comum.email': 'Correo electrónico',
    'comum.senha': 'Contraseña',
    'comum.entrar': 'Iniciar sesión',
    'comum.sair': 'Salir',
    'menu.painelUsuario': 'Panel de Usuario',
    'comum.erro': 'Error',
    'comum.sucesso': 'Éxito',
    'comum.carregando': 'Cargando',
    'comum.acoes.selecionar': 'Seleccionar',
    'comum.acoes.visualizar': 'Visualizar',
    'comum.acoes.editar': 'Editar',
    'comum.acoes.cancelar': 'Cancelar',
    'comum.acoes.salvar': 'Guardar',
    'comum.acoes.confirmar': 'Confirmar',
    'comum.acoes.remover': 'Eliminar',
    'dashboard.titulo': 'Panel',
    'dashboard.bem-vindo': '¡Bienvenido a Core!',
    'dashboard.saudacao-usuario': 'Hola, {{nome}}. Has iniciado sesión como {{perfil}}.',
    'dashboard.informacoes': 'Información del Usuario',
    'dashboard.modulos': 'Módulos Activos',
    'dashboard.nenhum-modulo': 'Ninguno',
    'dashboard.proximos-passos': 'Próximos pasos: Implementar módulo financiero',
    'dashboard.globalTitle': 'Visión General Financiera',
    'dashboard.globalDescription': 'Siga los principales indicadores financieros, movimientos recientes, desempeño anual y el balance consolidado de cuentas y tarjetas.',
    'dashboard.resumoFinanceiro': 'Resumen Financiero',
    'dashboard.graficoAreaSubarea': 'Gráfico circular por Área y Subárea',
    'dashboard.graficoAreaSubareaDescricao': 'Ingresos y gastos consolidados por área y subárea en el período filtrado.',
    'dashboard.graficoAreaSubareaCentro': 'Total Filtrado',
    'dashboard.graficoAnual': 'Gráfico Anual',
    'dashboard.ultimasTransacoes': 'Últimas Transacciones',
    'dashboard.balancoGeral': 'Balance General',
    'dashboard.saldoAtualConta': 'Saldo Actual de la Cuenta',
    'dashboard.saldoDisponivelCartao': 'Saldo Disponible de la Tarjeta',
    'dashboard.widget': 'Widget',
    'dashboard.reordenarHint': 'Arrastre los widgets o use las flechas para reorganizar el panel.',
    'dashboard.widgetGraficoInfo': 'Los valores siguen el idioma seleccionado y reflejan el filtro aplicado.',
    'dashboard.cards.receitas': 'Ingresos',
    'dashboard.cards.despesas': 'Gastos',
    'dashboard.cards.reembolsos': 'Reembolsos',
    'dashboard.cards.estornos': 'Estornos',
    'dashboard.cards.saldo': 'Saldo',
    'dashboard.widgets.resumo': 'Resumen Financiero',
    'dashboard.widgets.graficoAreaSubarea': 'Gráfico circular por Área y Subárea',
    'dashboard.widgets.graficoAnual': 'Gráfico Anual',
    'dashboard.widgets.ultimasTransacoes': 'Últimas Transacciones',
    'dashboard.widgets.balancoGeral': 'Balance General',
    'dashboard.colunas.id': 'ID',
    'dashboard.colunas.tipo': 'Tipo',
    'dashboard.colunas.valor': 'Valor',
    'dashboard.colunas.descricao': 'Descripción',
    'dashboard.colunas.dataEfetivacao': 'Fecha',
    'dashboard.colunas.tipoPagamento': 'Pago / Cobro',
    'dashboard.colunas.contaBancaria': 'Cuenta Bancaria',
    'dashboard.colunas.cartao': 'Tarjeta',
    'dashboard.colunas.areaSubarea': 'Área / Subárea',
    'dashboard.tipos.despesa': 'Gasto',
    'dashboard.tipos.receita': 'Ingreso',
    'dashboard.tipos.reembolso': 'Reembolso',
    'dashboard.tipos.estorno': 'Estorno',
    'dashboard.tiposBalanco.conta': 'Cuenta Bancaria',
    'dashboard.tiposBalanco.cartao': 'Tarjeta',
    'dashboard.pagamento.PIX': 'PIX',
    'dashboard.pagamento.TRANSFERENCIA': 'Transferencia',
    'dashboard.pagamento.CARTAO_CREDITO': 'Tarjeta de Crédito',
    'dashboard.pagamento.BOLETO': 'Boleta',
    'dashboard.pagamento.DINHEIRO': 'Efectivo',
    'dashboard.contas.BANCO_XP': 'Banco XP',
    'dashboard.contas.BANCO_DIGITAL': 'Banco Digital',
    'dashboard.contas.ITAU': 'Itaú',
    'dashboard.contas.NUBANK': 'Nubank',
    'dashboard.contas.INTER': 'Inter',
    'dashboard.descricoes.ALMOCO_CLIENTE': 'Almuerzo con cliente',
    'dashboard.descricoes.VENDA_SERVICO': 'Venta de servicio',
    'dashboard.descricoes.REEMBOLSO_VIAGEM': 'Reembolso de viaje',
    'dashboard.descricoes.ESTORNO_COBRANCA': 'Estorno de cobro',
    'dashboard.descricoes.ASSINATURA': 'Suscripción mensual',
    'dashboard.descricoes.SUPERMERCADO': 'Compra de supermercado',
    'dashboard.descricoes.COMBUSTIVEL': 'Combustible',
    'dashboard.descricoes.RECEBIMENTO': 'Cobro recurrente',
    'dashboard.areas.OPERACOES': 'Operaciones',
    'dashboard.areas.COMERCIAL': 'Comercial',
    'dashboard.areas.PESSOAL': 'Personal',
    'dashboard.areas.LAZER': 'Ocio',
    'dashboard.areas.TECNOLOGIA': 'Tecnología',
    'dashboard.areas.FINANCEIRO': 'Finanzas',
    'dashboard.areas.LOGISTICA': 'Logística',
    'dashboard.areas.JURIDICO': 'Jurídico',
    'dashboard.areas.ADMINISTRATIVO': 'Administrativo',
    'dashboard.areas.ATENDIMENTO': 'Atención',
    'dashboard.subareas.SUPRIMENTOS': 'Suministros',
    'dashboard.subareas.TRANSPORTE': 'Transporte',
    'dashboard.subareas.MANUTENCAO': 'Mantenimiento',
    'dashboard.subareas.VENDAS': 'Ventas',
    'dashboard.subareas.MARKETING': 'Marketing',
    'dashboard.subareas.EVENTOS': 'Eventos',
    'dashboard.subareas.SALARIOS': 'Salarios',
    'dashboard.subareas.BENEFICIOS': 'Beneficios',
    'dashboard.subareas.TREINAMENTO': 'Capacitación',
    'dashboard.subareas.VIAGENS': 'Viajes',
    'dashboard.subareas.CINEMA': 'Cine',
    'dashboard.subareas.RESTAURANTES': 'Restaurantes',
    'dashboard.subareas.SOFTWARE': 'Software',
    'dashboard.subareas.INFRAESTRUTURA': 'Infraestructura',
    'dashboard.subareas.LICENCAS': 'Licencias',
    'dashboard.subareas.IMPOSTOS': 'Impuestos',
    'dashboard.subareas.TARIFAS': 'Tarifas',
    'dashboard.subareas.INVESTIMENTOS': 'Inversiones',
    'dashboard.subareas.ARMAZENAGEM': 'Almacenaje',
    'dashboard.subareas.FRETES': 'Fletes',
    'dashboard.subareas.DISTRIBUICAO': 'Distribución',
    'dashboard.subareas.CONTRATOS': 'Contratos',
    'dashboard.subareas.CONSULTORIA': 'Consultoría',
    'dashboard.subareas.PROCESSOS': 'Procesos',
    'dashboard.subareas.FACILITIES': 'Instalaciones',
    'dashboard.subareas.VIAGENS_CORPORATIVAS': 'Viajes Corporativos',
    'dashboard.subareas.PATRIMONIO': 'Patrimonio',
    'dashboard.subareas.SUPORTE': 'Soporte',
    'dashboard.subareas.POS_VENDA': 'Posventa',
    'dashboard.subareas.OUVIDORIA': 'Atención al Cliente',
    'financeiro.despesas': 'Gastos',
    'financeiro.receitas': 'Ingresos',
    'financeiro.reembolsos': 'Reembolsos',
    'amigos.titulo': 'Amigos',
    'admin.titulo': 'Administración',
    'documentacao.titulo': 'Documentación - {{modulo}}',
    'documentacao.acao': 'Documentación',
    'documentacao.descricaoPadrao': 'Esta pantalla reúne los contenidos publicados para el módulo {{modulo}}. La información es mantenida por administración.',
    'documentacao.vazio': 'No hay documentación publicada para este módulo.',
    'documentacao.atualizadoEm': 'Actualizado el',
    'documentacao.modulos.dashboard': 'Panel',
    'documentacao.modulos.financeiro': 'Finanzas',
    'documentacao.modulos.amigos': 'Amigos',
    'documentacao.modulos.admin': 'Administración',
    'comum.login.esqueciSenha': 'Olvide mi contraseña',
    'comum.login.esqueciSenhaSucesso': 'Si el correo esta registrado, se enviaran las instrucciones de recuperacion.',
    'comum.login.credenciaisTeste': 'Use admin@core.com / 123456 para probar',
    'comum.login.tentativasRestantes': 'Intentos restantes: {{tentativas}}',
    'comum.login.erros.camposObrigatorios': 'Correo y Contraseña son obligatorios',
    'comum.login.erros.emailInvalido': 'Ingrese un correo valido',
    'comum.login.erros.emailObrigatorioRecuperacao': 'Ingrese el correo para recuperar la contraseña',
    'comum.login.erros.credenciaisInvalidas': 'Credenciales invalidas. Intentos restantes: {{tentativas}}',
    'comum.login.erros.bloqueadoTentativas': 'Inicio bloqueado despues de 5 intentos invalidos.',
    'primeiroAcesso.titulo': 'Cree su contraseña de acceso',
    'primeiroAcesso.descricao': 'En el primer inicio de sesión, es obligatorio definir una nueva contraseña.',
    'primeiroAcesso.campos.novaSenha': 'Nueva contraseña *',
    'primeiroAcesso.campos.confirmarSenha': 'Confirmar nueva contraseña *',
    'primeiroAcesso.botaoConfirmar': 'Confirmar contraseña',
    'primeiroAcesso.sucesso.senhaCriada': 'Contraseña creada con éxito.',
    'primeiroAcesso.erros.camposObrigatorios': 'Complete ambos campos de contraseña.',
    'primeiroAcesso.erros.senhaMinima': 'La contraseña debe tener al menos 10 caracteres.',
    'primeiroAcesso.erros.confirmacaoDiferente': 'La confirmación de contraseña no coincide.',
    'primeiroAcesso.erros.falhaCriarSenha': 'No fue posible crear la contraseña.',
    'usuarioPainel.titulo': 'Panel de Usuario',
    'usuarioPainel.informacoes': 'Información del Usuario',
    'usuarioPainel.nome': 'Nombre',
    'usuarioPainel.email': 'Correo',
    'usuarioPainel.perfil': 'Perfil de Acceso',
    'usuarioPainel.alterarSenha': 'Cambiar Contraseña',
    'usuarioPainel.campos.senhaAtual': 'Contraseña Actual *',
    'usuarioPainel.campos.novaSenha': 'Nueva Contraseña *',
    'usuarioPainel.campos.confirmarSenha': 'Confirmar Nueva Contraseña *',
    'usuarioPainel.botaoSalvar': 'Guardar Nueva Contraseña',
    'usuarioPainel.sucesso.senhaAlterada': 'Contraseña actualizada con éxito.',
    'usuarioPainel.erros.camposObrigatorios': 'Complete todos los campos de contraseña.',
    'usuarioPainel.erros.senhaMinima': 'La nueva contraseña debe tener al menos 10 caracteres.',
    'usuarioPainel.erros.confirmacaoDiferente': 'La confirmación de contraseña no coincide.',
    'usuarioPainel.erros.falhaAlterarSenha': 'No fue posible cambiar la contraseña.',
    'admin.documentacao.gerenciar': 'Gestionar Documentación',
    'admin.documentacao.novo': 'Nueva Documentación',
    'admin.documentacao.editar': 'Editar Documentación',
    'admin.documentacao.modulo': 'Módulo',
    'admin.documentacao.titulo': 'Título',
    'admin.documentacao.resumo': 'Resumen',
    'admin.documentacao.conteudo': 'Contenido',
    'admin.documentacao.placeholderTitulo': 'Ingrese el título de la documentación',
    'admin.documentacao.placeholderResumo': 'Describa brevemente el objetivo de este contenido',
    'admin.documentacao.placeholderConteudo': 'Explique funcionalidades, reglas y flujos del módulo',
    'admin.documentacao.salvoSucesso': 'Documentación guardada con éxito.',
    'admin.documentacao.publicadoSucesso': 'Documentación publicada con éxito.',
    'admin.documentacao.deletadoSucesso': 'Documentación eliminada con éxito.',
    'admin.documentacao.confirmarDelete': '¿Desea eliminar esta documentación?',
    'admin.documentacao.erros.camposObrigatorios': 'Título, resumen y contenido son obligatorios.',
    'financeiro.cartao.acoes.extrato': 'Extracto',
    'financeiro.cartao.extratoTitulo': 'Extracto de Gastos',
    'financeiro.cartao.extratoVazio': 'No se encontraron gastos para el mes seleccionado.',
    'financeiro.cartao.totalExtrato': 'Total del Extracto',
    'financeiro.cartao.titulo': 'Tarjetas',
    'financeiro.cartao.novo': 'Nueva Tarjeta',
    'financeiro.cartao.vazio': 'No se encontraron tarjetas.',
    'financeiro.cartao.campos.descricao': 'Descripción *',
    'financeiro.cartao.campos.bandeira': 'Marca *',
    'financeiro.cartao.campos.tipo': 'Tipo *',
    'financeiro.cartao.campos.limite': 'Límite *',
    'financeiro.cartao.campos.saldoDisponivel': 'Saldo Disponible *',
    'financeiro.cartao.campos.diaVencimento': 'Dia de Vencimiento *',
    'financeiro.cartao.campos.dataVencimentoCartao': 'Fecha de Vencimiento de la Tarjeta *',
    'financeiro.cartao.campos.status': 'Estado',
    'financeiro.cartao.placeholders.descricao': 'Ingrese la descripción de la tarjeta',
    'financeiro.cartao.placeholders.valor': '0,00',
    'financeiro.cartao.placeholders.data': 'DD/MM/AAAA',
    'financeiro.cartao.tipos.credito': 'Crédito',
    'financeiro.cartao.tipos.debito': 'Débito',
    'financeiro.cartao.status.ativo': 'ACTIVO',
    'financeiro.cartao.status.inativo': 'INACTIVO',
    'financeiro.cartao.acoes.fatura': 'Factura',
    'financeiro.cartao.acoes.ativar': 'Activar',
    'financeiro.cartao.acoes.inativar': 'Inactivar',
    'financeiro.cartao.faturaTitulo': 'Factura de la Tarjeta',
    'financeiro.cartao.faturaVazia': 'No se encontraron movimientos para el mes seleccionado.',
    'financeiro.cartao.totalFatura': 'Total de la Factura',
    'financeiro.cartao.mensagens.obrigatorio': 'Descripción, marca, tipo, límite, saldo disponible y fechas son obligatorios.',
    'financeiro.cartao.mensagens.obrigatorioCredito': 'Descripción, marca, tipo, límite, saldo disponible y fechas son obligatorios para tarjeta de crédito.',
    'financeiro.cartao.mensagens.obrigatorioDebito': 'Descripción, marca, tipo y saldo disponible son obligatorios para tarjeta de débito.',
    'financeiro.cartao.mensagens.criado': 'Tarjeta creada con éxito.',
    'financeiro.cartao.mensagens.atualizado': 'Tarjeta actualizada con éxito.',
    'financeiro.cartao.mensagens.transacoesPendentes': 'No es posible inactivar. Existen transacciones pendientes vinculadas a esta tarjeta.',
    'financeiro.cartao.mensagens.confirmarAtivacao': '¿Desea activar esta tarjeta?',
    'financeiro.cartao.mensagens.confirmarInativacao': '¿Desea inactivar esta tarjeta?',
    'financeiro.cartao.logs.titulo': 'Registros de cambios',
    'financeiro.cartao.logs.criado': 'Tarjeta creada con estado activo.',
    'financeiro.cartao.logs.atualizado': 'Los datos de la tarjeta fueron actualizados.',
    'financeiro.cartao.logs.ativado': 'Tarjeta activada.',
    'financeiro.cartao.logs.inativado': 'Tarjeta inactivada.',
    'financeiro.despesa.titulo': 'Gastos',
    'financeiro.despesa.nova': 'Nuevo Gasto',
    'financeiro.despesa.vazio': 'No se encontraron gastos.',
    'financeiro.despesa.campos.descricao': 'Descripción *',
    'financeiro.despesa.campos.observacao': 'Observacion',
    'financeiro.despesa.campos.dataLancamento': 'Fecha de Registro *',
    'financeiro.despesa.campos.dataVencimento': 'Fecha de Vencimiento *',
    'financeiro.despesa.campos.dataEfetivacao': 'Fecha de Liquidacion *',
    'financeiro.despesa.campos.tipoDespesa': 'Tipo de Gasto *',
    'financeiro.despesa.campos.tipoPagamento': 'Tipo de Pago *',
    'financeiro.despesa.campos.recorrencia': 'Recurrencia',
    'financeiro.despesa.campos.valorTotal': 'Valor Total *',
    'financeiro.despesa.campos.valorLiquido': 'Valor Neto',
    'financeiro.despesa.campos.valorEfetivacao': 'Valor de Liquidacion',
    'financeiro.despesa.campos.desconto': 'Descuento',
    'financeiro.despesa.campos.acrescimo': 'Recargo',
    'financeiro.despesa.campos.imposto': 'Impuesto',
    'financeiro.despesa.campos.juros': 'Interes',
    'financeiro.despesa.campos.rateioAmigos': 'Prorrateo con amigos',
    'financeiro.despesa.campos.rateioTipoDespesa': 'Prorrateo por tipo de gasto',
    'financeiro.despesa.campos.anexoDocumento': 'Adjunto de documento',
    'financeiro.despesa.campos.status': 'Estado',
    'financeiro.despesa.placeholders.descricao': 'Ingrese la descripción del gasto',
    'financeiro.despesa.placeholders.observacao': 'Ingrese observaciones adicionales',
    'financeiro.despesa.placeholders.data': 'DD/MM/AAAA',
    'financeiro.despesa.placeholders.valor': '0,00',
    'financeiro.despesa.placeholders.anexo': 'Nombre del archivo o documento',
    'financeiro.despesa.tipoDespesa.alimentacao': 'Alimentacion',
    'financeiro.despesa.tipoDespesa.transporte': 'Transporte',
    'financeiro.despesa.tipoDespesa.moradia': 'Vivienda',
    'financeiro.despesa.tipoDespesa.lazer': 'Ocio',
    'financeiro.despesa.tipoDespesa.saude': 'Salud',
    'financeiro.despesa.tipoDespesa.educacao': 'Educacion',
    'financeiro.despesa.tipoDespesa.servicos': 'Servicios',
    'financeiro.despesa.tipoPagamento.pix': 'PIX',
    'financeiro.despesa.tipoPagamento.cartaoCredito': 'Tarjeta de Crédito',
    'financeiro.despesa.tipoPagamento.cartaoDebito': 'Tarjeta de Débito',
    'financeiro.despesa.tipoPagamento.boleto': 'Boleta',
    'financeiro.despesa.tipoPagamento.transferencia': 'Transferencia',
    'financeiro.despesa.tipoPagamento.dinheiro': 'Efectivo',
    'financeiro.despesa.recorrencia.unica': 'Unica',
    'financeiro.despesa.recorrencia.semanal': 'Semanal',
    'financeiro.despesa.recorrencia.mensal': 'Mensual',
    'financeiro.despesa.recorrencia.anual': 'Anual',
    'financeiro.despesa.status.pendente': 'PENDIENTE',
    'financeiro.despesa.status.efetivada': 'LIQUIDADA',
    'financeiro.despesa.status.cancelada': 'CANCELADA',
    'financeiro.despesa.acoes.visualizar': 'Visualizar',
    'financeiro.despesa.acoes.efetivar': 'Liquidar',
    'financeiro.despesa.acoes.confirmarEfetivacao': 'Confirmar liquidacion',
    'financeiro.despesa.acoes.cancelarDespesa': 'Cancelar gasto',
    'financeiro.despesa.acoes.estornar': 'Revertir',
    'financeiro.despesa.mensagens.obrigatorio': 'Descripción, fechas, tipo de gasto y tipo de pago son obligatorios.',
    'financeiro.despesa.mensagens.valorObrigatorio': 'Ingrese el valor total del gasto.',
    'financeiro.despesa.mensagens.obrigatorioEfetivacao': 'Fecha de liquidacion, tipo de pago y valores son obligatorios.',
    'financeiro.despesa.mensagens.dataVencimentoMaiorQueLancamento': 'La fecha de vencimiento no puede ser menor que la fecha de lanzamiento.',
    'financeiro.despesa.mensagens.dataEfetivacaoMaiorQueLancamento': 'La fecha de liquidacion no puede ser menor que la fecha de lanzamiento.',
    'financeiro.despesa.mensagens.edicaoSomentePendente': 'El gasto solo puede editarse mientras este pendiente.',
    'financeiro.despesa.mensagens.efetivacaoSomentePendente': 'Solo los gastos pendientes pueden liquidarse.',
    'financeiro.despesa.mensagens.cancelamentoSomentePendente': 'Solo los gastos pendientes pueden cancelarse.',
    'financeiro.despesa.mensagens.estornoSomenteEfetivada': 'Solo los gastos liquidados pueden revertirse.',
    'financeiro.despesa.mensagens.confirmarCancelamento': '¿Desea cancelar este gasto?',
    'financeiro.despesa.mensagens.criada': 'Gasto creado con éxito.',
    'financeiro.despesa.mensagens.atualizada': 'Gasto actualizado con éxito.',
    'financeiro.despesa.mensagens.efetivada': 'Gasto liquidado con éxito.',
    'financeiro.despesa.mensagens.semObservacao': 'Sin observacion',
    'financeiro.despesa.logs.titulo': 'Historial de cambios',
    'financeiro.despesa.logs.criada': 'Gasto creado con estado pendiente.',
    'financeiro.despesa.logs.editada': 'Gasto editado mientras estaba pendiente.',
    'financeiro.despesa.logs.efetivada': 'Gasto liquidado con valor neto calculado.',
    'financeiro.despesa.logs.cancelada': 'Gasto cancelado mientras seguia pendiente.',
    'financeiro.despesa.logs.estornada': 'Gasto revertido y devuelto a pendiente.',
    'financeiro.comum.campos.subarea': 'Subárea',
    'financeiro.comum.campos.modoRecorrencia': 'Modo de recurrencia',
    'financeiro.comum.campos.quantidadeRecorrencia': 'Cantidad de recurrencias',
    'financeiro.comum.campos.quantidadeParcelas': 'Cantidad de cuotas',
    'financeiro.comum.opcoesRecorrencia.normal': 'Normal',
    'financeiro.comum.opcoesRecorrencia.fixa': 'Fija',
    'financeiro.comum.mensagens.quantidadeRecorrenciaMaiorQueZero': 'Ingrese una cantidad de recurrencias mayor que cero.',
    'financeiro.comum.mensagens.limiteRecorrenciaNormal': 'La recurrencia normal permite como maximo {límite} ocurrencias.',
    'financeiro.comum.mensagens.primeiraOcorrenciaGerada': 'Primera ocurrencia creada. Las demas se estan generando.',
    'financeiro.comum.mensagens.rateioDeveBaterValorTotal': 'La suma del prorrateo debe ser igual al valor total.',
    'financeiro.receita.titulo': 'Ingresos',
    'financeiro.receita.nova': 'Nuevo Ingreso',
    'financeiro.receita.vazio': 'No se encontraron ingresos.',
    'financeiro.receita.campos.descricao': 'Descripción *',
    'financeiro.receita.campos.observacao': 'Observacion',
    'financeiro.receita.campos.dataLancamento': 'Fecha de Registro *',
    'financeiro.receita.campos.dataVencimento': 'Fecha de Vencimiento *',
    'financeiro.receita.campos.dataEfetivacao': 'Fecha de Liquidacion *',
    'financeiro.receita.campos.tipoReceita': 'Tipo de Ingreso *',
    'financeiro.receita.campos.tipoRecebimento': 'Tipo de Cobro *',
    'financeiro.receita.campos.contaBancaria': 'Cuenta Bancaria',
    'financeiro.receita.campos.recorrencia': 'Recurrencia',
    'financeiro.receita.campos.valorTotal': 'Valor Total *',
    'financeiro.receita.campos.valorLiquido': 'Valor Neto',
    'financeiro.receita.campos.valorEfetivacao': 'Valor de Liquidacion',
    'financeiro.receita.campos.desconto': 'Descuento',
    'financeiro.receita.campos.acrescimo': 'Recargo',
    'financeiro.receita.campos.imposto': 'Impuesto',
    'financeiro.receita.campos.juros': 'Interes',
    'financeiro.receita.campos.rateioAmigos': 'Prorrateo con amigos',
    'financeiro.receita.campos.rateioAmigosValores': 'Valores prorrateados por amigo',
    'financeiro.receita.campos.rateioAreaSubarea': 'Prorrateo por área y subárea',
    'financeiro.receita.campos.rateioAreaSubareaValores': 'Valores prorrateados por área y subárea',
    'financeiro.receita.campos.anexoDocumento': 'Adjunto de documento',
    'financeiro.receita.campos.status': 'Estado',
    'financeiro.receita.placeholders.descricao': 'Ingrese la descripción del ingreso',
    'financeiro.receita.placeholders.observacao': 'Ingrese observaciones adicionales',
    'financeiro.receita.placeholders.data': 'DD/MM/AAAA',
    'financeiro.receita.placeholders.valor': '0,00',
    'financeiro.receita.placeholders.anexo': 'Seleccione un archivo',
    'financeiro.receita.tipoReceita.salario': 'Salario',
    'financeiro.receita.tipoReceita.freelance': 'Freelance',
    'financeiro.receita.tipoReceita.reembolso': 'Reembolso',
    'financeiro.receita.tipoReceita.investimento': 'Inversion',
    'financeiro.receita.tipoReceita.bonus': 'Bono',
    'financeiro.receita.tipoReceita.outros': 'Otros',
    'financeiro.receita.tipoRecebimento.pix': 'PIX',
    'financeiro.receita.tipoRecebimento.transferencia': 'Transferencia',
    'financeiro.receita.tipoRecebimento.contaCorrente': 'Cuenta Corriente',
    'financeiro.receita.tipoRecebimento.cartaoCredito': 'Tarjeta de Credito',
    'financeiro.receita.tipoRecebimento.cartaoDebito': 'Tarjeta de Debito',
    'financeiro.receita.tipoRecebimento.dinheiro': 'Efectivo',
    'financeiro.receita.tipoRecebimento.boleto': 'Boleta',
    'financeiro.receita.recorrencia.unica': 'Unica',
    'financeiro.receita.recorrencia.semanal': 'Semanal',
    'financeiro.receita.recorrencia.mensal': 'Mensual',
    'financeiro.receita.recorrencia.anual': 'Anual',
    'financeiro.receita.status.pendente': 'PENDIENTE',
    'financeiro.receita.status.efetivada': 'LIQUIDADA',
    'financeiro.receita.status.cancelada': 'CANCELADA',
    'financeiro.receita.acoes.visualizar': 'Visualizar',
    'financeiro.receita.acoes.efetivar': 'Liquidar',
    'financeiro.receita.acoes.confirmarEfetivacao': 'Confirmar liquidacion',
    'financeiro.receita.acoes.cancelarReceita': 'Cancelar ingreso',
    'financeiro.receita.acoes.estornar': 'Revertir',
    'financeiro.receita.mensagens.obrigatorio': 'Descripción, fechas, tipo de ingreso y tipo de cobro son obligatorios.',
    'financeiro.receita.mensagens.valorObrigatorio': 'Ingrese el valor total del ingreso.',
    'financeiro.receita.mensagens.contaObrigatoria': 'Seleccione la cuenta bancaria para este tipo de cobro.',
    'financeiro.receita.mensagens.obrigatorioEfetivacao': 'Fecha de liquidacion, tipo de cobro y valores son obligatorios.',
    'financeiro.receita.mensagens.dataVencimentoMaiorQueLancamento': 'La fecha de vencimiento no puede ser menor que la fecha de lanzamiento.',
    'financeiro.receita.mensagens.dataEfetivacaoMaiorQueLancamento': 'La fecha de liquidacion no puede ser menor que la fecha de lanzamiento.',
    'financeiro.receita.mensagens.edicaoSomentePendente': 'El ingreso solo puede editarse mientras este pendiente.',
    'financeiro.receita.mensagens.efetivacaoSomentePendente': 'Solo los ingresos pendientes pueden liquidarse.',
    'financeiro.receita.mensagens.cancelamentoSomentePendente': 'Solo los ingresos pendientes pueden cancelarse.',
    'financeiro.receita.mensagens.estornoSomenteEfetivada': 'Solo los ingresos liquidados pueden revertirse.',
    'financeiro.receita.mensagens.confirmarCancelamento': '¿Desea cancelar este ingreso?',
    'financeiro.receita.mensagens.criada': 'Ingreso creado con éxito.',
    'financeiro.receita.mensagens.atualizada': 'Ingreso actualizado con éxito.',
    'financeiro.receita.mensagens.efetivada': 'Ingreso liquidado con éxito.',
    'financeiro.receita.mensagens.semObservacao': 'Sin observacion',
    'financeiro.receita.logs.titulo': 'Historial de cambios',
    'financeiro.receita.logs.criada': 'Ingreso creado con estado pendiente.',
    'financeiro.receita.logs.editada': 'Ingreso editado mientras estaba pendiente.',
    'financeiro.receita.logs.efetivada': 'Ingreso liquidado con valor neto calculado.',
    'financeiro.receita.logs.cancelada': 'Ingreso cancelado mientras seguia pendiente.',
    'financeiro.receita.logs.estornada': 'Ingreso revertido y devuelto a pendiente.',
    'financeiro.contaBancaria.titulo': 'Cuentas Bancarias',
    'financeiro.contaBancaria.nova': 'Nueva Cuenta Bancaria',
    'financeiro.contaBancaria.vazio': 'No se encontraron cuentas bancarias.',
    'financeiro.contaBancaria.campos.descricao': 'Descripción *',
    'financeiro.contaBancaria.campos.banco': 'Banco *',
    'financeiro.contaBancaria.campos.agencia': 'Agencia *',
    'financeiro.contaBancaria.campos.numero': 'Número *',
    'financeiro.contaBancaria.campos.saldoInicial': 'Saldo Inicial *',
    'financeiro.contaBancaria.campos.saldoAtual': 'Saldo Actual',
    'financeiro.contaBancaria.campos.dataAbertura': 'Fecha de Apertura *',
    'financeiro.contaBancaria.campos.status': 'Estado',
    'financeiro.contaBancaria.placeholders.descricao': 'Ingrese la descripción de la cuenta',
    'financeiro.contaBancaria.placeholders.agencia': 'Ingrese la agencia',
    'financeiro.contaBancaria.placeholders.numero': 'Ingrese el número de la cuenta',
    'financeiro.contaBancaria.placeholders.saldoInicial': '0,00',
    'financeiro.contaBancaria.placeholders.dataAbertura': 'DD/MM/AAAA',
    'financeiro.contaBancaria.status.ativa': 'ACTIVA',
    'financeiro.contaBancaria.status.inativa': 'INACTIVA',
    'financeiro.contaBancaria.acoes.ativar': 'Activar',
    'financeiro.contaBancaria.acoes.inativar': 'Inactivar',
    'financeiro.contaBancaria.acoes.extrato': 'Extracto',
    'financeiro.contaBancaria.extratoTitulo': 'Extracto de la Cuenta',
    'financeiro.contaBancaria.extratoVazio': 'No se encontraron movimientos.',
    'financeiro.contaBancaria.tipos.credito': 'Crédito',
    'financeiro.contaBancaria.tipos.debito': 'Débito',
    'financeiro.contaBancaria.mensagens.obrigatorio': 'Descripción, banco, agencia, número, saldo inicial y fecha de apertura son obligatorios.',
    'financeiro.contaBancaria.mensagens.saldoObrigatorio': 'Ingrese el saldo inicial.',
    'financeiro.contaBancaria.mensagens.criada': 'Cuenta bancaria creada con éxito.',
    'financeiro.contaBancaria.mensagens.atualizada': 'Cuenta bancaria actualizada con éxito.',
    'financeiro.contaBancaria.mensagens.transacoesPendentes': 'No es posible inactivar la cuenta porque existen transacciones pendientes vinculadas.',
    'financeiro.contaBancaria.mensagens.confirmarAtivacao': '¿Desea activar esta cuenta bancaria?',
    'financeiro.contaBancaria.mensagens.confirmarInativacao': '¿Desea inactivar esta cuenta bancaria?',
    'financeiro.contaBancaria.logs.titulo': 'Historial de cambios',
    'financeiro.contaBancaria.logs.criada': 'Cuenta bancaria creada con estado activa.',
    'financeiro.contaBancaria.logs.atualizada': 'Cuenta bancaria actualizada.',
    'financeiro.contaBancaria.logs.ativada': 'Cuenta bancaria activada.',
    'financeiro.contaBancaria.logs.inativada': 'Cuenta bancaria inactivada.',
  },
};

const traducoesExtrasPorIdioma: Record<string, Record<string, string>> = {
  'pt-BR': {
    'menu.geral': 'Geral',
    'menu.painelUsuario': 'Painel do Usuário',
    'dashboard.informacoes': 'Informações do Usuário',
    'usuarioPainel.titulo': 'Painel do Usuário',
    'usuarioPainel.informacoes': 'Informações do Usuário',
    'admin.usuario.status': 'Status do Usuário',
    'admin.usuario.statusAtivo': 'Ativo',
    'admin.usuario.statusInativo': 'Inativo',
    'admin.usuario.permissoesTitulo': 'Módulos, telas e funcionalidades',
  },
  en: {
    'menu.geral': 'General',
    'menu.painelUsuario': 'User Panel',
    'dashboard.informacoes': 'User Information',
    'usuarioPainel.titulo': 'User Panel',
    'usuarioPainel.informacoes': 'User Information',
    'admin.usuario.status': 'User Status',
    'admin.usuario.statusAtivo': 'Active',
    'admin.usuario.statusInativo': 'Inactive',
    'admin.usuario.permissoesTitulo': 'Modules, screens and features',
  },
  es: {
    'menu.geral': 'General',
    'menu.painelUsuario': 'Panel del Usuario',
    'dashboard.informacoes': 'Información del Usuario',
    'usuarioPainel.titulo': 'Panel del Usuario',
    'usuarioPainel.informacoes': 'Información del Usuario',
    'admin.usuario.status': 'Estado del Usuario',
    'admin.usuario.statusAtivo': 'Activo',
    'admin.usuario.statusInativo': 'Inactivo',
    'admin.usuario.permissoesTitulo': 'Módulos, pantallas y funcionalidades',
  },
};

export const usarTraducao = () => {
  const { t: i18nT } = useTranslation(['comum', 'financeiro']);

  const interpolar = (texto: string, opcoes?: Record<string, string>) => {
    if (!opcoes) return texto;
    return Object.entries(opcoes).reduce((resultado, [chave, valor]) => {
      const marcador = new RegExp(`\\{\\{\\s*${chave}\\s*\\}\\}`, 'g');
      return resultado.replace(marcador, String(valor));
    }, texto);
  };

  const t = (chave: string, opcoes?: Record<string, string>): string => {
    let resultado = '';
    let chaveInterna = chave;

    if (chave.startsWith('comum.') || chave.startsWith('financeiro.')) {
      const [ns, ...resto] = chave.split('.');
      chaveInterna = resto.join('.');
      resultado = String(i18nT(`${ns}:${chaveInterna}`, opcoes as any));
    } else {
      resultado = String(i18nT(`comum:${chave}`, opcoes as any));
      if (resultado === `comum:${chave}`) {
        resultado = String(i18nT(`financeiro:${chave}`, opcoes as any));
      }
    }

    if (
      resultado === chave ||
      resultado === chaveInterna ||
      resultado === `comum:${chave}` ||
      resultado === `financeiro:${chave}`
    ) {
      const idiomaAtual = i18n.resolvedLanguage || i18n.language || 'pt-BR';
      const idiomaBase = idiomaAtual.startsWith('en') ? 'en' : idiomaAtual.startsWith('es') ? 'es' : 'pt-BR';

      const buscarRecurso = (ns: 'comum' | 'financeiro', key: string) => {
        const atual = i18n.getResource(idiomaAtual, ns, key);
        if (typeof atual === 'string') return atual;
        const base = i18n.getResource(idiomaBase, ns, key);
        if (typeof base === 'string') return base;
        const padrao = i18n.getResource('pt-BR', ns, key);
        return typeof padrao === 'string' ? padrao : '';
      };

      if (chave.startsWith('comum.')) {
        const recurso = buscarRecurso('comum', chaveInterna);
        if (recurso) return normalizarMojibake(interpolar(recurso, opcoes));
      } else if (chave.startsWith('financeiro.')) {
        const recurso = buscarRecurso('financeiro', chaveInterna);
        if (recurso) return normalizarMojibake(interpolar(recurso, opcoes));
      } else {
        const comum = buscarRecurso('comum', chave);
        if (comum) return normalizarMojibake(interpolar(comum, opcoes));
        const financeiro = buscarRecurso('financeiro', chave);
        if (financeiro) return normalizarMojibake(interpolar(financeiro, opcoes));
      }

      const extras = traducoesExtrasPorIdioma[idiomaBase] || traducoesExtrasPorIdioma['pt-BR'];
      if (extras[chave]) {
        return normalizarMojibake(interpolar(extras[chave], opcoes));
      }

      const fallbackIdioma = fallbackPorIdioma[idiomaBase] || fallbackPorIdioma['pt-BR'];
      const fallbackTexto = fallbackIdioma?.[chave] || fallbackPorIdioma['pt-BR']?.[chave];
      if (fallbackTexto) {
        return normalizarMojibake(interpolar(fallbackTexto, opcoes));
      }

      return chave;
    }

    return normalizarMojibake(resultado);
  };

  return { t };
};




